import SharedCCD

/-!
# Machine-generated audit certificate — do not edit

Generated by src/sigml/audit.py from Cell Ontology (biology) definition 'large pre-B-II cell = pre-B-II cell ∩ (CL:4030045 some PR:000003457)' (order embeddings).
Entities were embedded, placements quantized to ℤ^6,
and the structure audited against the spec in ConceptualSpace.lean.
Only concepts and definitions that PASSED the audit appear here;
every proof below is closed by `decide`, so acceptance of this file
by the Lean kernel certifies that the audited structure satisfies
the formal spec.
-/

namespace AuditCertOBO

inductive E
  | cl0000008 | cl0000011 | cl0000016 | cl0000020 | cl0000022 | cl0000024 | cl0000953 | cl0002051 | cl0002053
  deriving DecidableEq, Fintype

/-- The shared entity placement: the CCD's quality dimensions. -/
def posE : E → Point 6
  | .cl0000008 => ![12, 26, 0, 0, 0, 11]
  | .cl0000011 => ![0, 17, 0, 6, 0, 30]
  | .cl0000016 => ![0, 9, 9, 0, 24, 11]
  | .cl0000020 => ![0, 0, 0, 14, 26, 10]
  | .cl0000022 => ![10, 16, 0, 0, 23, 11]
  | .cl0000024 => ![32, 0, 3, 16, 0, 0]
  | .cl0000953 => ![0, 23, 16, 19, 0, 0]
  | .cl0002051 => ![6, 22, 12, 12, 0, 0]
  | .cl0002053 => ![0, 22, 16, 13, 0, 0]

def preBIiCellMembers : List E := [.cl0000953, .cl0002051, .cl0002053]
/-- Attention profile of pre-B-II cell (total 240). -/
def wPreBIiCell : Fin 6 → ℕ := ![26, 41, 48, 33, 46, 46]
def preBIiCellChi : E → Point 6 := weightedChi wPreBIiCell posE

def kPreBIiCell : KonceptN 6 E where
  pred := fun a => a ∈ preBIiCellMembers
  χ    := preBIiCellChi

def diffLargePreBIiCellMembers : List E := [.cl0000953, .cl0002051]
/-- Attention profile of diff::large pre-B-II cell (total 240). -/
def wDiffLargePreBIiCell : Fin 6 → ℕ := ![21, 43, 45, 38, 46, 47]
def diffLargePreBIiCellChi : E → Point 6 := weightedChi wDiffLargePreBIiCell posE

def kDiffLargePreBIiCell : KonceptN 6 E where
  pred := fun a => a ∈ diffLargePreBIiCellMembers
  χ    := diffLargePreBIiCellChi

def largePreBIiCellMembers : List E := [.cl0000953, .cl0002051]
/-- Attention profile of large pre-B-II cell (total 240). -/
def wLargePreBIiCell : Fin 6 → ℕ := ![21, 43, 45, 38, 46, 47]
def largePreBIiCellChi : E → Point 6 := weightedChi wLargePreBIiCell posE

def kLargePreBIiCell : KonceptN 6 E where
  pred := fun a => a ∈ largePreBIiCellMembers
  χ    := largePreBIiCellChi

/-- CCD grounding for pre-B-II cell: CL:0000953 and CL:0002051 cluster against CL:0000008. -/
theorem preBIiCell_ccd_cl0000953_cl0002051 :
    SimilarByContrastN (preBIiCellChi .cl0000953) (preBIiCellChi .cl0002051) (preBIiCellChi .cl0000008) := by decide

/-- CCD grounding for pre-B-II cell: CL:0000953 and CL:0002053 cluster against CL:0000008. -/
theorem preBIiCell_ccd_cl0000953_cl0002053 :
    SimilarByContrastN (preBIiCellChi .cl0000953) (preBIiCellChi .cl0002053) (preBIiCellChi .cl0000008) := by decide

/-- CCD grounding for pre-B-II cell: CL:0002051 and CL:0002053 cluster against CL:0000008. -/
theorem preBIiCell_ccd_cl0002051_cl0002053 :
    SimilarByContrastN (preBIiCellChi .cl0002051) (preBIiCellChi .cl0002053) (preBIiCellChi .cl0000008) := by decide

/-- CCD grounding for diff::large pre-B-II cell: CL:0000953 and CL:0002051 cluster against CL:0000008. -/
theorem diffLargePreBIiCell_ccd_cl0000953_cl0002051 :
    SimilarByContrastN (diffLargePreBIiCellChi .cl0000953) (diffLargePreBIiCellChi .cl0002051) (diffLargePreBIiCellChi .cl0000008) := by decide

/-- CCD grounding for large pre-B-II cell: CL:0000953 and CL:0002051 cluster against CL:0000008. -/
theorem largePreBIiCell_ccd_cl0000953_cl0002051 :
    SimilarByContrastN (largePreBIiCellChi .cl0000953) (largePreBIiCellChi .cl0002051) (largePreBIiCellChi .cl0000008) := by decide

-- Definition 'large pre-B-II cell = diff::large pre-B-II cell pre-B-II cell' FAILED the audit; not certified.
--   ✗ isEssential: unit CL:0000953: genus χ (0, 943, 768, 627, 0, 0) ⊀ (incomparable or reversed) differentia χ (0, 989, 720, 722, 0, 0); uniform-functional collapse HOLDS (2338 vs 2431)
--   ✗ isEssential: unit CL:0002051: genus χ (156, 902, 576, 396, 0, 0) ⊀ (incomparable or reversed) differentia χ (126, 946, 540, 456, 0, 0); uniform-functional collapse HOLDS (2030 vs 2068)

/-- The uniform depth functional: equal attention to every dimension. -/
def uniform : DepthFunctional 6 :=
  ⟨fun _ => 1, fun _ => Int.zero_lt_one⟩

/-- Weaker certificate for 'large pre-B-II cell = diff::large pre-B-II cell pre-B-II cell': the product-order
    raise fails (genus and differentia attentions are
    incomparable), but under the uniform functional the
    differentia is deeper on every unit. Direction is
    imposed by the weighting, not discovered — exactly
    what `functionals_disagree` warns. -/
theorem largePreBIiCell_functional_essential :
    ∀ a, (a ∈ preBIiCellMembers ∧ a ∈ diffLargePreBIiCellMembers) →
      Raise (uniform.eval (preBIiCellChi a)) (uniform.eval (diffLargePreBIiCellChi a)) := by
  decide

end AuditCertOBO
