import SharedCCD

/-!
# Machine-generated audit certificate — do not edit

Generated by src/sigml/audit.py from WordNet Carnivora (trained order embeddings).
Entities were embedded, placements quantized to ℤ^5,
and the structure audited against the spec in ConceptualSpace.lean.
Only concepts and definitions that PASSED the audit appear here;
every proof below is closed by `decide`, so acceptance of this file
by the Lean kernel certifies that the audited structure satisfies
the formal spec.
-/

namespace AuditCertWordNet

inductive E
  | dogN01 | lionN01 | tigerN02 | wolfN01
  deriving DecidableEq, Fintype

/-- The shared entity placement: the CCD's quality dimensions. -/
def posE : E → Point 5
  | .dogN01 => ![0, 9, 20, 21, 0]
  | .lionN01 => ![0, 10, 0, 9, 20]
  | .tigerN02 => ![10, 0, 1, 4, 25]
  | .wolfN01 => ![0, 0, 20, 0, 24]

def canineN02Members : List E := [.dogN01, .wolfN01]
/-- Attention profile of canine.n.02 (total 240). -/
def wCanineN02 : Fin 5 → ℕ := ![30, 3, 119, 24, 64]
def canineN02Chi : E → Point 5 := weightedChi wCanineN02 posE

def kCanineN02 : KonceptN 5 E where
  pred := fun a => a ∈ canineN02Members
  χ    := canineN02Chi

def felineN01Members : List E := [.lionN01, .tigerN02]
/-- Attention profile of feline.n.01 (total 240). -/
def wFelineN01 : Fin 5 → ℕ := ![30, 3, 119, 24, 64]
def felineN01Chi : E → Point 5 := weightedChi wFelineN01 posE

def kFelineN01 : KonceptN 5 E where
  pred := fun a => a ∈ felineN01Members
  χ    := felineN01Chi

/-- CCD grounding for canine.n.02: dog.n.01 and wolf.n.01 cluster against lion.n.01. -/
theorem canineN02_ccd_dogN01_wolfN01 :
    SimilarByContrastN (canineN02Chi .dogN01) (canineN02Chi .wolfN01) (canineN02Chi .lionN01) := by decide

/-- CCD grounding for feline.n.01: lion.n.01 and tiger.n.02 cluster against dog.n.01. -/
theorem felineN01_ccd_lionN01_tigerN02 :
    SimilarByContrastN (felineN01Chi .lionN01) (felineN01Chi .tigerN02) (felineN01Chi .dogN01) := by decide

end AuditCertWordNet
