import SharedCCD

/-!
# Machine-generated audit certificate — do not edit

Generated by src/sigml/audit.py from a learned order embedding.
Entities were embedded, placements quantized to ℤ^3,
and the structure audited against the spec in ConceptualSpace.lean.
Only concepts and definitions that PASSED the audit appear here;
every proof below is closed by `decide`, so acceptance of this file
by the Lean kernel certifies that the learned structure satisfies
the formal spec.
-/

namespace AuditCert

inductive E
  | socrates | hypatia | rex | luna | tom | tweety | oak
  deriving DecidableEq, Fintype

/-- The shared entity placement: the CCD's quality dimensions. -/
def posE : E → Point 3
  | .socrates => ![11, 7, 2]
  | .hypatia => ![11, 4, 2]
  | .rex => ![3, 8, 19]
  | .luna => ![4, 0, 10]
  | .tom => ![0, 8, 12]
  | .tweety => ![3, 8, 0]
  | .oak => ![3, 8, 0]

def animalMembers : List E := [.socrates, .hypatia, .rex, .luna, .tom, .tweety]
/-- Attention profile of animal (total 240). -/
def wAnimal : Fin 3 → ℕ := ![47, 43, 150]
def animalChi : E → Point 3 := weightedChi wAnimal posE

def kAnimal : KonceptN 3 E where
  pred := fun a => a ∈ animalMembers
  χ    := animalChi

def rationalMembers : List E := [.socrates, .hypatia]
/-- Attention profile of rational (total 240). -/
def wRational : Fin 3 → ℕ := ![118, 7, 115]
def rationalChi : E → Point 3 := weightedChi wRational posE

def kRational : KonceptN 3 E where
  pred := fun a => a ∈ rationalMembers
  χ    := rationalChi

def humanMembers : List E := [.socrates, .hypatia]
/-- Attention profile of human (total 240). -/
def wHuman : Fin 3 → ℕ := ![130, 14, 96]
def humanChi : E → Point 3 := weightedChi wHuman posE

def kHuman : KonceptN 3 E where
  pred := fun a => a ∈ humanMembers
  χ    := humanChi

def canidMembers : List E := [.rex, .luna]
/-- Attention profile of canid (total 240). -/
def wCanid : Fin 3 → ℕ := ![31, 44, 165]
def canidChi : E → Point 3 := weightedChi wCanid posE

def kCanid : KonceptN 3 E where
  pred := fun a => a ∈ canidMembers
  χ    := canidChi

def domesticMembers : List E := [.rex, .tom]
/-- Attention profile of domestic (total 240). -/
def wDomestic : Fin 3 → ℕ := ![38, 120, 82]
def domesticChi : E → Point 3 := weightedChi wDomestic posE

def kDomestic : KonceptN 3 E where
  pred := fun a => a ∈ domesticMembers
  χ    := domesticChi

def dogMembers : List E := [.rex]
/-- Attention profile of dog (total 240). -/
def wDog : Fin 3 → ℕ := ![29, 27, 184]
def dogChi : E → Point 3 := weightedChi wDog posE

def kDog : KonceptN 3 E where
  pred := fun a => a ∈ dogMembers
  χ    := dogChi

/-- CCD grounding for animal: socrates and hypatia cluster against oak. -/
theorem animal_ccd_socrates_hypatia :
    SimilarByContrastN (animalChi .socrates) (animalChi .hypatia) (animalChi .oak) := by decide

/-- CCD grounding for animal: rex and luna cluster against oak. -/
theorem animal_ccd_rex_luna :
    SimilarByContrastN (animalChi .rex) (animalChi .luna) (animalChi .oak) := by decide

/-- CCD grounding for animal: rex and tom cluster against oak. -/
theorem animal_ccd_rex_tom :
    SimilarByContrastN (animalChi .rex) (animalChi .tom) (animalChi .oak) := by decide

/-- CCD grounding for animal: luna and tom cluster against oak. -/
theorem animal_ccd_luna_tom :
    SimilarByContrastN (animalChi .luna) (animalChi .tom) (animalChi .oak) := by decide

/-- CCD grounding for rational: socrates and hypatia cluster against rex. -/
theorem rational_ccd_socrates_hypatia :
    SimilarByContrastN (rationalChi .socrates) (rationalChi .hypatia) (rationalChi .rex) := by decide

/-- CCD grounding for human: socrates and hypatia cluster against rex. -/
theorem human_ccd_socrates_hypatia :
    SimilarByContrastN (humanChi .socrates) (humanChi .hypatia) (humanChi .rex) := by decide

/-- CCD grounding for canid: rex and luna cluster against tweety. -/
theorem canid_ccd_rex_luna :
    SimilarByContrastN (canidChi .rex) (canidChi .luna) (canidChi .tweety) := by decide

/-- CCD grounding for domestic: rex and tom cluster against socrates. -/
theorem domestic_ccd_rex_tom :
    SimilarByContrastN (domesticChi .rex) (domesticChi .tom) (domesticChi .socrates) := by decide

-- Definition 'human = rational animal' FAILED the audit; not certified.
--   ✗ isEssential: unit socrates: genus χ (517, 301, 300) ⊀ (incomparable or reversed) differentia χ (1298, 49, 230); uniform-functional collapse HOLDS (1118 vs 1577)
--   ✗ isEssential: unit hypatia: genus χ (517, 172, 300) ⊀ (incomparable or reversed) differentia χ (1298, 28, 230); uniform-functional collapse HOLDS (989 vs 1556)

/-- The uniform depth functional: equal attention to every dimension. -/
def uniform : DepthFunctional 3 :=
  ⟨fun _ => 1, fun _ => Int.zero_lt_one⟩

/-- Weaker certificate for 'human = rational animal': the product-order
    raise fails (genus and differentia attentions are
    incomparable), but under the uniform functional the
    differentia is deeper on every unit. Direction is
    imposed by the weighting, not discovered — exactly
    what `functionals_disagree` warns. -/
theorem human_functional_essential :
    ∀ a, (a ∈ animalMembers ∧ a ∈ rationalMembers) →
      Raise (uniform.eval (animalChi a)) (uniform.eval (rationalChi a)) := by
  decide

-- Definition 'dog = domestic canid' FAILED the audit; not certified.
--   ✗ isEssential: unit rex: genus χ (93, 352, 3135) ⊀ (incomparable or reversed) differentia χ (114, 960, 1558); uniform-functional collapse fails (3580 vs 2632)
--   ✗ has_two_units: definiendum has 1 unit(s); essential definitions need two (KonceptDefN.has_two_units)

end AuditCert
