import ConceptualSpace

/-!
# Machine-generated audit certificate — do not edit

Generated by src/sigml/audit.py from a learned order embedding.
Entities were embedded, placements quantized to ℤ^3,
and the structure audited against the spec in ConceptualSpace.lean.
Only concepts and definitions that PASSED the audit appear here;
every proof below is closed by `decide`, so acceptance of this file
by the Lean kernel certifies that the learned structure satisfies
the formal spec.
-/

namespace AuditCert

inductive E
  | socrates | hypatia | rex | luna | tom | tweety | oak
  deriving DecidableEq, Fintype

def animalMembers : List E := [.socrates, .hypatia, .rex, .luna, .tom, .tweety]
def animalChi : E → Point 3
  | .socrates => ![378, 152, 139]
  | .hypatia => ![378, 76, 139]
  | .rex => ![63, 152, 1251]
  | .luna => ![126, 0, 695]
  | .tom => ![0, 152, 834]
  | .tweety => ![63, 152, 0]
  | .oak => ![63, 152, 0]

def kAnimal : KonceptN 3 E where
  pred := fun a => a ∈ animalMembers
  χ    := animalChi

def rationalMembers : List E := [.socrates, .hypatia]
def rationalChi : E → Point 3
  | .socrates => ![798, 0, 107]
  | .hypatia => ![798, 0, 107]
  | .rex => ![133, 0, 963]
  | .luna => ![266, 0, 535]
  | .tom => ![0, 0, 642]
  | .tweety => ![133, 0, 0]
  | .oak => ![133, 0, 0]

def kRational : KonceptN 3 E where
  pred := fun a => a ∈ rationalMembers
  χ    := rationalChi

def humanMembers : List E := [.socrates, .hypatia]
def humanChi : E → Point 3
  | .socrates => ![876, 24, 88]
  | .hypatia => ![876, 12, 88]
  | .rex => ![146, 24, 792]
  | .luna => ![292, 0, 440]
  | .tom => ![0, 24, 528]
  | .tweety => ![146, 24, 0]
  | .oak => ![146, 24, 0]

def kHuman : KonceptN 3 E where
  pred := fun a => a ∈ humanMembers
  χ    := humanChi

def canidMembers : List E := [.rex, .luna]
def canidChi : E → Point 3
  | .socrates => ![228, 184, 156]
  | .hypatia => ![228, 92, 156]
  | .rex => ![38, 184, 1404]
  | .luna => ![76, 0, 780]
  | .tom => ![0, 184, 936]
  | .tweety => ![38, 184, 0]
  | .oak => ![38, 184, 0]

def kCanid : KonceptN 3 E where
  pred := fun a => a ∈ canidMembers
  χ    := canidChi

def domesticMembers : List E := [.rex, .tom]
def domesticChi : E → Point 3
  | .socrates => ![270, 480, 75]
  | .hypatia => ![270, 240, 75]
  | .rex => ![45, 480, 675]
  | .luna => ![90, 0, 375]
  | .tom => ![0, 480, 450]
  | .tweety => ![45, 480, 0]
  | .oak => ![45, 480, 0]

def kDomestic : KonceptN 3 E where
  pred := fun a => a ∈ domesticMembers
  χ    := domesticChi

def dogMembers : List E := [.rex]
def dogChi : E → Point 3
  | .socrates => ![252, 100, 173]
  | .hypatia => ![252, 50, 173]
  | .rex => ![42, 100, 1557]
  | .luna => ![84, 0, 865]
  | .tom => ![0, 100, 1038]
  | .tweety => ![42, 100, 0]
  | .oak => ![42, 100, 0]

def kDog : KonceptN 3 E where
  pred := fun a => a ∈ dogMembers
  χ    := dogChi

/-- CCD grounding for animal: socrates and hypatia cluster against oak. -/
theorem animal_ccd_socrates_hypatia :
    SimilarByContrastN (animalChi .socrates) (animalChi .hypatia) (animalChi .oak) := by decide

/-- CCD grounding for animal: rex and luna cluster against oak. -/
theorem animal_ccd_rex_luna :
    SimilarByContrastN (animalChi .rex) (animalChi .luna) (animalChi .oak) := by decide

/-- CCD grounding for animal: rex and tom cluster against oak. -/
theorem animal_ccd_rex_tom :
    SimilarByContrastN (animalChi .rex) (animalChi .tom) (animalChi .oak) := by decide

/-- CCD grounding for animal: luna and tom cluster against oak. -/
theorem animal_ccd_luna_tom :
    SimilarByContrastN (animalChi .luna) (animalChi .tom) (animalChi .oak) := by decide

/-- CCD grounding for human: socrates and hypatia cluster against rex. -/
theorem human_ccd_socrates_hypatia :
    SimilarByContrastN (humanChi .socrates) (humanChi .hypatia) (humanChi .rex) := by decide

/-- CCD grounding for canid: rex and luna cluster against socrates. -/
theorem canid_ccd_rex_luna :
    SimilarByContrastN (canidChi .rex) (canidChi .luna) (canidChi .socrates) := by decide

/-- CCD grounding for domestic: rex and tom cluster against socrates. -/
theorem domestic_ccd_rex_tom :
    SimilarByContrastN (domesticChi .rex) (domesticChi .tom) (domesticChi .socrates) := by decide

-- Definition 'human = rational animal' FAILED the audit; not certified.
--   ✗ isEssential: unit socrates: genus χ (378, 152, 139) ⊀ (incomparable or reversed) differentia χ (798, 0, 107); uniform-functional collapse HOLDS (669 vs 905)
--   ✗ isEssential: unit hypatia: genus χ (378, 76, 139) ⊀ (incomparable or reversed) differentia χ (798, 0, 107); uniform-functional collapse HOLDS (593 vs 905)

/-- The uniform depth functional: equal attention to every dimension. -/
def uniform : DepthFunctional 3 :=
  ⟨fun _ => 1, fun _ => Int.zero_lt_one⟩

/-- Weaker certificate for 'human = rational animal': the product-order
    raise fails (genus and differentia attentions are
    incomparable), but under the uniform functional the
    differentia is deeper on every unit. Direction is
    imposed by the weighting, not discovered — exactly
    what `functionals_disagree` warns. -/
theorem human_functional_essential :
    ∀ a, (a ∈ animalMembers ∧ a ∈ rationalMembers) →
      Raise (uniform.eval (animalChi a)) (uniform.eval (rationalChi a)) := by
  decide

-- Definition 'dog = domestic canid' FAILED the audit; not certified.
--   ✗ isEssential: unit rex: genus χ (38, 184, 1404) ⊀ (incomparable or reversed) differentia χ (45, 480, 675); uniform-functional collapse fails (1626 vs 1200)
--   ✗ has_two_units: definiendum has 1 unit(s); essential definitions need two (KonceptDefN.has_two_units)

end AuditCert
