import SharedCCD

/-!
# Machine-generated audit certificate — do not edit

Generated by src/sigml/audit.py from Environment Ontology (non-biological: geography, climate, materials) definition 'marine thermocline = thermocline ∩ (BFO:0000050 some marine water body)' (order embeddings).
Entities were embedded, placements quantized to ℤ^6,
and the structure audited against the spec in ConceptualSpace.lean.
Only concepts and definitions that PASSED the audit appear here;
every proof below is closed by `decide`, so acceptance of this file
by the Lean kernel certifies that the audited structure satisfies
the formal spec.
-/

namespace AuditCertENVO

inductive E
  | envo00000038 | envo00000053 | envo00000054 | envo00000057 | envo00000058 | envo00000085 | envo00002132 | envo01000106 | envo01000107
  deriving DecidableEq, Fintype

/-- The shared entity placement: the CCD's quality dimensions. -/
def posE : E → Point 6
  | .envo00000038 => ![0, 0, 0, 17, 57, 0]
  | .envo00000053 => ![0, 0, 33, 60, 0, 0]
  | .envo00000054 => ![0, 91, 0, 0, 0, 0]
  | .envo00000057 => ![0, 0, 109, 0, 0, 0]
  | .envo00000058 => ![39, 43, 0, 0, 0, 0]
  | .envo00000085 => ![0, 45, 0, 0, 25, 0]
  | .envo00002132 => ![0, 16, 31, 28, 0, 0]
  | .envo01000106 => ![0, 21, 31, 45, 0, 0]
  | .envo01000107 => ![0, 19, 44, 31, 0, 0]

def thermoclineMembers : List E := [.envo00002132, .envo01000106, .envo01000107]
/-- Attention profile of thermocline (total 240). -/
def wThermocline : Fin 6 → ℕ := ![24, 41, 43, 81, 51, 0]
def thermoclineChi : E → Point 6 := weightedChi wThermocline posE

def kThermocline : KonceptN 6 E where
  pred := fun a => a ∈ thermoclineMembers
  χ    := thermoclineChi

def diffMarineThermoclineMembers : List E := [.envo01000106, .envo01000107]
/-- Attention profile of diff::marine thermocline (total 240). -/
def wDiffMarineThermocline : Fin 6 → ℕ := ![22, 31, 50, 91, 46, 0]
def diffMarineThermoclineChi : E → Point 6 := weightedChi wDiffMarineThermocline posE

def kDiffMarineThermocline : KonceptN 6 E where
  pred := fun a => a ∈ diffMarineThermoclineMembers
  χ    := diffMarineThermoclineChi

def marineThermoclineMembers : List E := [.envo01000106, .envo01000107]
/-- Attention profile of marine thermocline (total 240). -/
def wMarineThermocline : Fin 6 → ℕ := ![22, 31, 50, 91, 46, 0]
def marineThermoclineChi : E → Point 6 := weightedChi wMarineThermocline posE

def kMarineThermocline : KonceptN 6 E where
  pred := fun a => a ∈ marineThermoclineMembers
  χ    := marineThermoclineChi

/-- CCD grounding for thermocline: ENVO:00002132 and ENVO:01000106 cluster against ENVO:00000038. -/
theorem thermocline_ccd_envo00002132_envo01000106 :
    SimilarByContrastN (thermoclineChi .envo00002132) (thermoclineChi .envo01000106) (thermoclineChi .envo00000038) := by decide

/-- CCD grounding for thermocline: ENVO:00002132 and ENVO:01000107 cluster against ENVO:00000038. -/
theorem thermocline_ccd_envo00002132_envo01000107 :
    SimilarByContrastN (thermoclineChi .envo00002132) (thermoclineChi .envo01000107) (thermoclineChi .envo00000038) := by decide

/-- CCD grounding for thermocline: ENVO:01000106 and ENVO:01000107 cluster against ENVO:00000038. -/
theorem thermocline_ccd_envo01000106_envo01000107 :
    SimilarByContrastN (thermoclineChi .envo01000106) (thermoclineChi .envo01000107) (thermoclineChi .envo00000038) := by decide

/-- CCD grounding for diff::marine thermocline: ENVO:01000106 and ENVO:01000107 cluster against ENVO:00000038. -/
theorem diffMarineThermocline_ccd_envo01000106_envo01000107 :
    SimilarByContrastN (diffMarineThermoclineChi .envo01000106) (diffMarineThermoclineChi .envo01000107) (diffMarineThermoclineChi .envo00000038) := by decide

/-- CCD grounding for marine thermocline: ENVO:01000106 and ENVO:01000107 cluster against ENVO:00000038. -/
theorem marineThermocline_ccd_envo01000106_envo01000107 :
    SimilarByContrastN (marineThermoclineChi .envo01000106) (marineThermoclineChi .envo01000107) (marineThermoclineChi .envo00000038) := by decide

-- Definition 'marine thermocline = diff::marine thermocline thermocline' FAILED the audit; not certified.
--   ✗ isEssential: unit ENVO:01000106: genus χ (0, 861, 1333, 3645, 0, 0) ⊀ (incomparable or reversed) differentia χ (0, 651, 1550, 4095, 0, 0); uniform-functional collapse HOLDS (5839 vs 6296)
--   ✗ isEssential: unit ENVO:01000107: genus χ (0, 779, 1892, 2511, 0, 0) ⊀ (incomparable or reversed) differentia χ (0, 589, 2200, 2821, 0, 0); uniform-functional collapse HOLDS (5182 vs 5610)

/-- The uniform depth functional: equal attention to every dimension. -/
def uniform : DepthFunctional 6 :=
  ⟨fun _ => 1, fun _ => Int.zero_lt_one⟩

/-- Weaker certificate for 'marine thermocline = diff::marine thermocline thermocline': the product-order
    raise fails (genus and differentia attentions are
    incomparable), but under the uniform functional the
    differentia is deeper on every unit. Direction is
    imposed by the weighting, not discovered — exactly
    what `functionals_disagree` warns. -/
theorem marineThermocline_functional_essential :
    ∀ a, (a ∈ thermoclineMembers ∧ a ∈ diffMarineThermoclineMembers) →
      Raise (uniform.eval (thermoclineChi a)) (uniform.eval (diffMarineThermoclineChi a)) := by
  decide

end AuditCertENVO
