import SharedCCD

/-!
# Machine-generated audit certificate — do not edit

Generated by src/sigml/audit.py from Environment Ontology (non-biological: geography, climate, materials) definition 'marine thermocline = thermocline ∩ (BFO:0000050 some marine water body)' (order embeddings).
Entities were embedded, placements quantized to ℤ^6,
and the structure audited against the spec in ConceptualSpace.lean.
Only concepts and definitions that PASSED the audit appear here;
every proof below is closed by `decide`, so acceptance of this file
by the Lean kernel certifies that the audited structure satisfies
the formal spec.
-/

namespace AuditCertENVO

inductive E
  | envo00000038 | envo00000053 | envo00000054 | envo00000057 | envo00000058 | envo00000085 | envo00002132 | envo01000106 | envo01000107
  deriving DecidableEq, Fintype

/-- The shared entity placement: the CCD's quality dimensions. -/
def posE : E → Point 6
  | .envo00000038 => ![0, 10, 18, 0, 23, 0]
  | .envo00000053 => ![26, 22, 0, 0, 0, 0]
  | .envo00000054 => ![0, 0, 9, 8, 37, 0]
  | .envo00000057 => ![2, 28, 0, 19, 12, 0]
  | .envo00000058 => ![29, 0, 0, 0, 18, 0]
  | .envo00000085 => ![0, 0, 0, 35, 11, 8]
  | .envo00002132 => ![14, 0, 0, 0, 38, 0]
  | .envo01000106 => ![13, 0, 0, 0, 49, 0]
  | .envo01000107 => ![10, 0, 10, 0, 43, 0]

def thermoclineMembers : List E := [.envo00002132, .envo01000106, .envo01000107]
/-- Attention profile of thermocline (total 240). -/
def wThermocline : Fin 6 → ℕ := ![13, 46, 5, 48, 122, 6]
def thermoclineChi : E → Point 6 := weightedChi wThermocline posE

def kThermocline : KonceptN 6 E where
  pred := fun a => a ∈ thermoclineMembers
  χ    := thermoclineChi

def diffMarineThermoclineMembers : List E := [.envo01000106, .envo01000107]
/-- Attention profile of diff::marine thermocline (total 240). -/
def wDiffMarineThermocline : Fin 6 → ℕ := ![7, 44, 6, 45, 132, 6]
def diffMarineThermoclineChi : E → Point 6 := weightedChi wDiffMarineThermocline posE

def kDiffMarineThermocline : KonceptN 6 E where
  pred := fun a => a ∈ diffMarineThermoclineMembers
  χ    := diffMarineThermoclineChi

def marineThermoclineMembers : List E := [.envo01000106, .envo01000107]
/-- Attention profile of marine thermocline (total 240). -/
def wMarineThermocline : Fin 6 → ℕ := ![7, 44, 6, 45, 132, 6]
def marineThermoclineChi : E → Point 6 := weightedChi wMarineThermocline posE

def kMarineThermocline : KonceptN 6 E where
  pred := fun a => a ∈ marineThermoclineMembers
  χ    := marineThermoclineChi

/-- CCD grounding for thermocline: ENVO:00002132 and ENVO:01000106 cluster against ENVO:00000038. -/
theorem thermocline_ccd_envo00002132_envo01000106 :
    SimilarByContrastN (thermoclineChi .envo00002132) (thermoclineChi .envo01000106) (thermoclineChi .envo00000038) := by decide

/-- CCD grounding for thermocline: ENVO:00002132 and ENVO:01000107 cluster against ENVO:00000038. -/
theorem thermocline_ccd_envo00002132_envo01000107 :
    SimilarByContrastN (thermoclineChi .envo00002132) (thermoclineChi .envo01000107) (thermoclineChi .envo00000038) := by decide

/-- CCD grounding for thermocline: ENVO:01000106 and ENVO:01000107 cluster against ENVO:00000038. -/
theorem thermocline_ccd_envo01000106_envo01000107 :
    SimilarByContrastN (thermoclineChi .envo01000106) (thermoclineChi .envo01000107) (thermoclineChi .envo00000038) := by decide

/-- CCD grounding for diff::marine thermocline: ENVO:01000106 and ENVO:01000107 cluster against ENVO:00000038. -/
theorem diffMarineThermocline_ccd_envo01000106_envo01000107 :
    SimilarByContrastN (diffMarineThermoclineChi .envo01000106) (diffMarineThermoclineChi .envo01000107) (diffMarineThermoclineChi .envo00000038) := by decide

/-- CCD grounding for marine thermocline: ENVO:01000106 and ENVO:01000107 cluster against ENVO:00000038. -/
theorem marineThermocline_ccd_envo01000106_envo01000107 :
    SimilarByContrastN (marineThermoclineChi .envo01000106) (marineThermoclineChi .envo01000107) (marineThermoclineChi .envo00000038) := by decide

-- Definition 'marine thermocline = diff::marine thermocline thermocline' FAILED the audit; not certified.
--   ✗ isEssential: unit ENVO:01000106: genus χ (169, 0, 0, 0, 5978, 0) ⊀ (incomparable or reversed) differentia χ (91, 0, 0, 0, 6468, 0); uniform-functional collapse HOLDS (6147 vs 6559)
--   ✗ isEssential: unit ENVO:01000107: genus χ (130, 0, 50, 0, 5246, 0) ⊀ (incomparable or reversed) differentia χ (70, 0, 60, 0, 5676, 0); uniform-functional collapse HOLDS (5426 vs 5806)

/-- The uniform depth functional: equal attention to every dimension. -/
def uniform : DepthFunctional 6 :=
  ⟨fun _ => 1, fun _ => Int.zero_lt_one⟩

/-- Weaker certificate for 'marine thermocline = diff::marine thermocline thermocline': the product-order
    raise fails (genus and differentia attentions are
    incomparable), but under the uniform functional the
    differentia is deeper on every unit. Direction is
    imposed by the weighting, not discovered — exactly
    what `functionals_disagree` warns. -/
theorem marineThermocline_functional_essential :
    ∀ a, (a ∈ thermoclineMembers ∧ a ∈ diffMarineThermoclineMembers) →
      Raise (uniform.eval (thermoclineChi a)) (uniform.eval (diffMarineThermoclineChi a)) := by
  decide

end AuditCertENVO
