import SharedCCD

/-!
# Machine-generated audit certificate — do not edit

Generated by src/sigml/audit.py from Cell Ontology (biology) definition 'CD8-alpha alpha positive, gamma-delta intraepithelial T cell = gamma-delta intraepithelial T cell ∩ (RO:0002104 some PR:000001084)' (order embeddings).
Entities were embedded, placements quantized to ℤ^6,
and the structure audited against the spec in ConceptualSpace.lean.
Only concepts and definitions that PASSED the audit appear here;
every proof below is closed by `decide`, so acceptance of this file
by the Lean kernel certifies that the audited structure satisfies
the formal spec.
-/

namespace AuditCertOBO

inductive E
  | cl0000008 | cl0000011 | cl0000016 | cl0000020 | cl0000022 | cl0000024 | cl0000803 | cl0002513 | cl0002514
  deriving DecidableEq, Fintype

/-- The shared entity placement: the CCD's quality dimensions. -/
def posE : E → Point 6
  | .cl0000008 => ![27, 0, 0, 31, 0, 35]
  | .cl0000011 => ![0, 15, 7, 0, 83, 0]
  | .cl0000016 => ![0, 49, 54, 0, 0, 0]
  | .cl0000020 => ![37, 26, 0, 0, 12, 0]
  | .cl0000022 => ![0, 53, 64, 0, 0, 0]
  | .cl0000024 => ![45, 31, 0, 0, 0, 0]
  | .cl0000803 => ![0, 44, 0, 26, 13, 0]
  | .cl0002513 => ![0, 43, 0, 24, 12, 0]
  | .cl0002514 => ![0, 51, 0, 27, 15, 0]

def gammaDeltaIntraepithelialTCellMembers : List E := [.cl0000803, .cl0002513, .cl0002514]
/-- Attention profile of gamma-delta intraepithelial T cell (total 240). -/
def wGammaDeltaIntraepithelialTCell : Fin 6 → ℕ := ![51, 48, 59, 58, 7, 17]
def gammaDeltaIntraepithelialTCellChi : E → Point 6 := weightedChi wGammaDeltaIntraepithelialTCell posE

def kGammaDeltaIntraepithelialTCell : KonceptN 6 E where
  pred := fun a => a ∈ gammaDeltaIntraepithelialTCellMembers
  χ    := gammaDeltaIntraepithelialTCellChi

def diffCd8AlphaAlphaPositiveGammaDeltaIntraepithelialTCellMembers : List E := [.cl0002513, .cl0002514]
/-- Attention profile of diff::CD8-alpha alpha positive, gamma-delta intraepithelial T cell (total 240). -/
def wDiffCd8AlphaAlphaPositiveGammaDeltaIntraepithelialTCell : Fin 6 → ℕ := ![51, 52, 58, 57, 6, 16]
def diffCd8AlphaAlphaPositiveGammaDeltaIntraepithelialTCellChi : E → Point 6 := weightedChi wDiffCd8AlphaAlphaPositiveGammaDeltaIntraepithelialTCell posE

def kDiffCd8AlphaAlphaPositiveGammaDeltaIntraepithelialTCell : KonceptN 6 E where
  pred := fun a => a ∈ diffCd8AlphaAlphaPositiveGammaDeltaIntraepithelialTCellMembers
  χ    := diffCd8AlphaAlphaPositiveGammaDeltaIntraepithelialTCellChi

def cd8AlphaAlphaPositiveGammaDeltaIntraepithelialTCellMembers : List E := [.cl0002513, .cl0002514]
/-- Attention profile of CD8-alpha alpha positive, gamma-delta intraepithelial T cell (total 240). -/
def wCd8AlphaAlphaPositiveGammaDeltaIntraepithelialTCell : Fin 6 → ℕ := ![51, 52, 58, 57, 6, 16]
def cd8AlphaAlphaPositiveGammaDeltaIntraepithelialTCellChi : E → Point 6 := weightedChi wCd8AlphaAlphaPositiveGammaDeltaIntraepithelialTCell posE

def kCd8AlphaAlphaPositiveGammaDeltaIntraepithelialTCell : KonceptN 6 E where
  pred := fun a => a ∈ cd8AlphaAlphaPositiveGammaDeltaIntraepithelialTCellMembers
  χ    := cd8AlphaAlphaPositiveGammaDeltaIntraepithelialTCellChi

/-- CCD grounding for gamma-delta intraepithelial T cell: CL:0000803 and CL:0002513 cluster against CL:0000008. -/
theorem gammaDeltaIntraepithelialTCell_ccd_cl0000803_cl0002513 :
    SimilarByContrastN (gammaDeltaIntraepithelialTCellChi .cl0000803) (gammaDeltaIntraepithelialTCellChi .cl0002513) (gammaDeltaIntraepithelialTCellChi .cl0000008) := by decide

/-- CCD grounding for gamma-delta intraepithelial T cell: CL:0000803 and CL:0002514 cluster against CL:0000008. -/
theorem gammaDeltaIntraepithelialTCell_ccd_cl0000803_cl0002514 :
    SimilarByContrastN (gammaDeltaIntraepithelialTCellChi .cl0000803) (gammaDeltaIntraepithelialTCellChi .cl0002514) (gammaDeltaIntraepithelialTCellChi .cl0000008) := by decide

/-- CCD grounding for gamma-delta intraepithelial T cell: CL:0002513 and CL:0002514 cluster against CL:0000008. -/
theorem gammaDeltaIntraepithelialTCell_ccd_cl0002513_cl0002514 :
    SimilarByContrastN (gammaDeltaIntraepithelialTCellChi .cl0002513) (gammaDeltaIntraepithelialTCellChi .cl0002514) (gammaDeltaIntraepithelialTCellChi .cl0000008) := by decide

/-- CCD grounding for diff::CD8-alpha alpha positive, gamma-delta intraepithelial T cell: CL:0002513 and CL:0002514 cluster against CL:0000008. -/
theorem diffCd8AlphaAlphaPositiveGammaDeltaIntraepithelialTCell_ccd_cl0002513_cl0002514 :
    SimilarByContrastN (diffCd8AlphaAlphaPositiveGammaDeltaIntraepithelialTCellChi .cl0002513) (diffCd8AlphaAlphaPositiveGammaDeltaIntraepithelialTCellChi .cl0002514) (diffCd8AlphaAlphaPositiveGammaDeltaIntraepithelialTCellChi .cl0000008) := by decide

/-- CCD grounding for CD8-alpha alpha positive, gamma-delta intraepithelial T cell: CL:0002513 and CL:0002514 cluster against CL:0000008. -/
theorem cd8AlphaAlphaPositiveGammaDeltaIntraepithelialTCell_ccd_cl0002513_cl0002514 :
    SimilarByContrastN (cd8AlphaAlphaPositiveGammaDeltaIntraepithelialTCellChi .cl0002513) (cd8AlphaAlphaPositiveGammaDeltaIntraepithelialTCellChi .cl0002514) (cd8AlphaAlphaPositiveGammaDeltaIntraepithelialTCellChi .cl0000008) := by decide

-- Definition 'CD8-alpha alpha positive, gamma-delta intraepithelial T cell = diff::CD8-alpha alpha positive, gamma-delta intraepithelial T cell gamma-delta intraepithelial T cell' FAILED the audit; not certified.
--   ✗ isEssential: unit CL:0002513: genus χ (0, 2064, 0, 1392, 84, 0) ⊀ (incomparable or reversed) differentia χ (0, 2236, 0, 1368, 72, 0); uniform-functional collapse HOLDS (3540 vs 3676)
--   ✗ isEssential: unit CL:0002514: genus χ (0, 2448, 0, 1566, 105, 0) ⊀ (incomparable or reversed) differentia χ (0, 2652, 0, 1539, 90, 0); uniform-functional collapse HOLDS (4119 vs 4281)

/-- The uniform depth functional: equal attention to every dimension. -/
def uniform : DepthFunctional 6 :=
  ⟨fun _ => 1, fun _ => Int.zero_lt_one⟩

/-- Weaker certificate for 'CD8-alpha alpha positive, gamma-delta intraepithelial T cell = diff::CD8-alpha alpha positive, gamma-delta intraepithelial T cell gamma-delta intraepithelial T cell': the product-order
    raise fails (genus and differentia attentions are
    incomparable), but under the uniform functional the
    differentia is deeper on every unit. Direction is
    imposed by the weighting, not discovered — exactly
    what `functionals_disagree` warns. -/
theorem cd8AlphaAlphaPositiveGammaDeltaIntraepithelialTCell_functional_essential :
    ∀ a, (a ∈ gammaDeltaIntraepithelialTCellMembers ∧ a ∈ diffCd8AlphaAlphaPositiveGammaDeltaIntraepithelialTCellMembers) →
      Raise (uniform.eval (gammaDeltaIntraepithelialTCellChi a)) (uniform.eval (diffCd8AlphaAlphaPositiveGammaDeltaIntraepithelialTCellChi a)) := by
  decide

end AuditCertOBO
