import ConceptualSpace

/-!
# Machine-generated audit certificate — do not edit

Generated by src/sigml/audit.py from a learned order embedding.
Entities were embedded, placements quantized to ℤ^3,
and the structure audited against the spec in ConceptualSpace.lean.
Only concepts and definitions that PASSED the audit appear here;
every proof below is closed by `decide`, so acceptance of this file
by the Lean kernel certifies that the learned structure satisfies
the formal spec.
-/

namespace AuditCert

inductive E
  | socrates | hypatia | rex | luna | tom | tweety | oak
  deriving DecidableEq, Fintype

def animalMembers : List E := [.socrates, .hypatia, .rex, .luna, .tom, .tweety]
def animalChi : E → Point 3
  | .socrates => ![0, 0, 0]
  | .hypatia => ![0, 0, 0]
  | .rex => ![0, 0, 0]
  | .luna => ![0, 0, 0]
  | .tom => ![0, 0, 0]
  | .tweety => ![0, 0, 0]
  | .oak => ![0, 0, 0]

def kAnimal : KonceptN 3 E where
  pred := fun a => a ∈ animalMembers
  χ    := animalChi

def rationalMembers : List E := [.socrates, .hypatia]
def rationalChi : E → Point 3
  | .socrates => ![8, 2, 0]
  | .hypatia => ![8, 1, 0]
  | .rex => ![2, 2, 2]
  | .luna => ![3, 0, 1]
  | .tom => ![0, 2, 1]
  | .tweety => ![2, 2, 0]
  | .oak => ![2, 2, 0]

def kRational : KonceptN 3 E where
  pred := fun a => a ∈ rationalMembers
  χ    := rationalChi

def humanMembers : List E := [.socrates, .hypatia]
def humanChi : E → Point 3
  | .socrates => ![8, 2, 0]
  | .hypatia => ![8, 1, 0]
  | .rex => ![2, 2, 2]
  | .luna => ![3, 0, 1]
  | .tom => ![0, 2, 1]
  | .tweety => ![2, 2, 0]
  | .oak => ![2, 2, 0]

def kHuman : KonceptN 3 E where
  pred := fun a => a ∈ humanMembers
  χ    := humanChi

def canidMembers : List E := [.rex, .luna]
def canidChi : E → Point 3
  | .socrates => ![3, 0, 1]
  | .hypatia => ![3, 0, 1]
  | .rex => ![1, 0, 12]
  | .luna => ![1, 0, 6]
  | .tom => ![0, 0, 7]
  | .tweety => ![1, 0, 0]
  | .oak => ![1, 0, 0]

def kCanid : KonceptN 3 E where
  pred := fun a => a ∈ canidMembers
  χ    := canidChi

def domesticMembers : List E := [.rex, .tom]
def domesticChi : E → Point 3
  | .socrates => ![0, 4, 1]
  | .hypatia => ![0, 2, 1]
  | .rex => ![0, 4, 14]
  | .luna => ![0, 0, 7]
  | .tom => ![0, 4, 9]
  | .tweety => ![0, 4, 0]
  | .oak => ![0, 4, 0]

def kDomestic : KonceptN 3 E where
  pred := fun a => a ∈ domesticMembers
  χ    := domesticChi

def dogMembers : List E := [.rex]
def dogChi : E → Point 3
  | .socrates => ![2, 3, 2]
  | .hypatia => ![2, 2, 2]
  | .rex => ![1, 4, 22]
  | .luna => ![1, 0, 12]
  | .tom => ![0, 4, 14]
  | .tweety => ![1, 4, 0]
  | .oak => ![1, 4, 0]

def kDog : KonceptN 3 E where
  pred := fun a => a ∈ dogMembers
  χ    := dogChi

/-- CCD grounding for rational: socrates and hypatia cluster against rex. -/
theorem rational_ccd_socrates_hypatia :
    SimilarByContrastN (rationalChi .socrates) (rationalChi .hypatia) (rationalChi .rex) := by decide

/-- CCD grounding for human: socrates and hypatia cluster against rex. -/
theorem human_ccd_socrates_hypatia :
    SimilarByContrastN (humanChi .socrates) (humanChi .hypatia) (humanChi .rex) := by decide

/-- CCD grounding for canid: rex and luna cluster against socrates. -/
theorem canid_ccd_rex_luna :
    SimilarByContrastN (canidChi .rex) (canidChi .luna) (canidChi .socrates) := by decide

/-- CCD grounding for domestic: rex and tom cluster against socrates. -/
theorem domestic_ccd_rex_tom :
    SimilarByContrastN (domesticChi .rex) (domesticChi .tom) (domesticChi .socrates) := by decide

/-- Certified essential definition: human = rational animal. A term of `KonceptDefN` IS the certificate. -/
def defHuman : KonceptDefN 3 E where
  definiendum := kAnimal.meet kRational
  genus       := kAnimal
  differentia := kRational
  isMeet      := rfl
  isEssential := by
    show ∀ a, (a ∈ animalMembers ∧ a ∈ rationalMembers) →
      RaiseProd (animalChi a) (rationalChi a)
    decide
  ccd := {
    k        := kAnimal.meet kRational
    a        := .socrates
    b        := .hypatia
    contrast := .rex
    ha       := by show E.socrates ∈ animalMembers ∧ E.socrates ∈ rationalMembers; decide
    hb       := by show E.hypatia ∈ animalMembers ∧ E.hypatia ∈ rationalMembers; decide
    hc       := by show ¬(E.rex ∈ animalMembers ∧ E.rex ∈ rationalMembers); decide
    hab      := by decide
    similar  := by
      show SimilarByContrastN
        (fun i => max (animalChi (E.socrates) i) (rationalChi (E.socrates) i))
        (fun i => max (animalChi (E.hypatia) i) (rationalChi (E.hypatia) i))
        (fun i => max (animalChi (E.rex) i) (rationalChi (E.rex) i))
      decide }
  ccd_concept  := rfl
  ccd_contrast := by show ¬(E.rex ∈ rationalMembers); decide

/-- Downstream theorems come free once the term exists: e.g. two units. -/
example : ∃ a b, (kAnimal.meet kRational).pred a ∧ (kAnimal.meet kRational).pred b ∧ a ≠ b :=
  defHuman.has_two_units

-- Definition 'dog = domestic canid' FAILED the audit; not certified.
--   ✗ isEssential: unit rex: genus χ (1, 0, 12) ⊀ (incomparable or reversed) differentia χ (0, 4, 14)
--   ✗ has_two_units: definiendum has 1 unit(s); essential definitions need two (KonceptDefN.has_two_units)

end AuditCert
