import SharedCCD

/-!
# Machine-generated audit certificate — do not edit

Generated by src/sigml/audit.py from a hand-crafted fixture exercising the KonceptDefCCD path.
Entities were embedded, placements quantized to ℤ^2,
and the structure audited against the spec in ConceptualSpace.lean.
Only concepts and definitions that PASSED the audit appear here;
every proof below is closed by `decide`, so acceptance of this file
by the Lean kernel certifies that the audited structure satisfies
the formal spec.
-/

namespace AuditCertSynthetic

inductive E
  | ada | bee | cat | dot
  deriving DecidableEq, Fintype

/-- The shared entity placement: the CCD's quality dimensions. -/
def posE : E → Point 2
  | .ada => ![0, 2]
  | .bee => ![0, 3]
  | .cat => ![5, 0]
  | .dot => ![9, 9]

def genusgMembers : List E := [.ada, .bee, .cat]
/-- Attention profile of genusG (total 240). -/
def wGenusg : Fin 2 → ℕ := ![200, 40]
def genusgChi : E → Point 2 := weightedChi wGenusg posE

def kGenusg : KonceptN 2 E where
  pred := fun a => a ∈ genusgMembers
  χ    := genusgChi

def diffdMembers : List E := [.ada, .bee]
/-- Attention profile of diffD (total 240). -/
def wDiffd : Fin 2 → ℕ := ![40, 200]
def diffdChi : E → Point 2 := weightedChi wDiffd posE

def kDiffd : KonceptN 2 E where
  pred := fun a => a ∈ diffdMembers
  χ    := diffdChi

def deffMembers : List E := [.ada, .bee]
/-- Attention profile of defF (total 240). -/
def wDeff : Fin 2 → ℕ := ![200, 40]
def deffChi : E → Point 2 := weightedChi wDeff posE

def kDeff : KonceptN 2 E where
  pred := fun a => a ∈ deffMembers
  χ    := deffChi

/-- CCD grounding for genusG: ada and bee cluster against dot. -/
theorem genusg_ccd_ada_bee :
    SimilarByContrastN (genusgChi .ada) (genusgChi .bee) (genusgChi .dot) := by decide

/-- CCD grounding for genusG: ada and cat cluster against dot. -/
theorem genusg_ccd_ada_cat :
    SimilarByContrastN (genusgChi .ada) (genusgChi .cat) (genusgChi .dot) := by decide

/-- CCD grounding for genusG: bee and cat cluster against dot. -/
theorem genusg_ccd_bee_cat :
    SimilarByContrastN (genusgChi .bee) (genusgChi .cat) (genusgChi .dot) := by decide

/-- CCD grounding for diffD: ada and bee cluster against cat. -/
theorem diffd_ccd_ada_bee :
    SimilarByContrastN (diffdChi .ada) (diffdChi .bee) (diffdChi .cat) := by decide

/-- CCD grounding for defF: ada and bee cluster against cat. -/
theorem deff_ccd_ada_bee :
    SimilarByContrastN (deffChi .ada) (deffChi .bee) (deffChi .cat) := by decide

/-- Certified essential definition: defF = diffD genusG, on a SHARED
    conceptual common denominator: one placement, two
    commensurate attention profiles. A term of `KonceptDefCCD`
    IS the certificate — and its essentiality verdict is
    provably invariant under change of the common unit
    (`KonceptDefCCD.essential_rescale`). -/
def defDeff : KonceptDefCCD 2 E where
  definiendum := kGenusg.meet kDiffd
  genus       := kGenusg
  differentia := kDiffd
  isMeet      := rfl
  pos         := posE
  wG          := wGenusg
  wD          := wDiffd
  commensurate := by decide
  genusScale  := rfl
  diffScale   := rfl
  isEssential := by
    show ∀ a, (a ∈ genusgMembers ∧ a ∈ diffdMembers) →
      RaiseProd (genusgChi a) (diffdChi a)
    decide
  ccd := {
    k        := kGenusg.meet kDiffd
    a        := .ada
    b        := .bee
    contrast := .cat
    ha       := by show E.ada ∈ genusgMembers ∧ E.ada ∈ diffdMembers; decide
    hb       := by show E.bee ∈ genusgMembers ∧ E.bee ∈ diffdMembers; decide
    hc       := by show ¬(E.cat ∈ genusgMembers ∧ E.cat ∈ diffdMembers); decide
    hab      := by decide
    similar  := by
      show SimilarByContrastN
        (fun i => max (genusgChi (E.ada) i) (diffdChi (E.ada) i))
        (fun i => max (genusgChi (E.bee) i) (diffdChi (E.bee) i))
        (fun i => max (genusgChi (E.cat) i) (diffdChi (E.cat) i))
      decide }
  ccd_concept  := rfl
  ccd_contrast := by show ¬(E.cat ∈ diffdMembers); decide

/-- Downstream theorems come free once the term exists: e.g. two units. -/
example : ∃ a b, (kGenusg.meet kDiffd).pred a ∧ (kGenusg.meet kDiffd).pred b ∧ a ≠ b :=
  defDeff.has_two_units

end AuditCertSynthetic
