import SharedCCD

/-!
# Machine-generated audit certificate — do not edit

Generated by src/sigml/audit.py from Environment Ontology (non-biological: geography, climate, materials) definition 'formation of a solid aerosol in an atmosphere = atmospheric aerosol formation ∩ (RO:0002234 some aerosolised solids)' (order embeddings).
Entities were embedded, placements quantized to ℤ^6,
and the structure audited against the spec in ConceptualSpace.lean.
Only concepts and definitions that PASSED the audit appear here;
every proof below is closed by `decide`, so acceptance of this file
by the Lean kernel certifies that the audited structure satisfies
the formal spec.
-/

namespace AuditCertENVO

inductive E
  | envo00000172 | envo00000173 | envo00000183 | envo00002125 | envo00002132 | envo00002153 | envo00002210 | envo00002211 | envo00002213 | envo01000106 | envo01000107 | envo01000212 | envo01000227 | envo01000228 | envo01000382 | envo01000384 | envo01000385 | envo01000387 | envo01000388 | envo01000389 | envo01000390 | envo01000391 | envo01000401 | envo01000402 | envo01000834 | envo01000836 | envo01001090 | envo01001091 | envo01001640 | envo01001735 | envo01001736 | envo01001737 | envo01001798 | envo03520006 | envo03600010 | envo03600077
  deriving DecidableEq, Fintype

/-- The shared entity placement: the CCD's quality dimensions. -/
def posE : E → Point 6
  | .envo00000172 => ![0, 21, 0, 1, 0, 23]
  | .envo00000173 => ![0, 13, 0, 0, 8, 23]
  | .envo00000183 => ![0, 12, 0, 13, 0, 22]
  | .envo00002125 => ![0, 25, 27, 9, 0, 0]
  | .envo00002132 => ![10, 0, 0, 12, 7, 32]
  | .envo00002153 => ![0, 0, 13, 12, 9, 15]
  | .envo00002210 => ![22, 0, 12, 0, 0, 0]
  | .envo00002211 => ![1, 25, 27, 0, 9, 0]
  | .envo00002213 => ![10, 25, 27, 0, 0, 0]
  | .envo01000106 => ![10, 0, 0, 13, 32, 0]
  | .envo01000107 => ![10, 0, 9, 13, 23, 0]
  | .envo01000212 => ![13, 0, 0, 0, 31, 20]
  | .envo01000227 => ![2, 0, 10, 42, 0, 0]
  | .envo01000228 => ![13, 0, 0, 37, 0, 0]
  | .envo01000382 => ![0, 12, 0, 0, 0, 37]
  | .envo01000384 => ![0, 6, 37, 0, 7, 0]
  | .envo01000385 => ![0, 2, 13, 25, 12, 0]
  | .envo01000387 => ![0, 0, 2, 25, 0, 19]
  | .envo01000388 => ![0, 12, 0, 26, 9, 0]
  | .envo01000389 => ![6, 0, 0, 0, 18, 30]
  | .envo01000390 => ![0, 0, 0, 9, 27, 32]
  | .envo01000391 => ![0, 0, 12, 0, 6, 25]
  | .envo01000401 => ![0, 20, 8, 0, 21, 9]
  | .envo01000402 => ![0, 0, 13, 0, 22, 22]
  | .envo01000834 => ![0, 17, 19, 6, 7, 4]
  | .envo01000836 => ![0, 15, 20, 0, 0, 8]
  | .envo01001090 => ![29, 0, 8, 0, 0, 12]
  | .envo01001091 => ![16, 14, 0, 0, 10, 0]
  | .envo01001640 => ![29, 10, 0, 0, 0, 10]
  | .envo01001735 => ![36, 0, 0, 10, 0, 14]
  | .envo01001736 => ![35, 0, 0, 10, 11, 0]
  | .envo01001737 => ![22, 9, 0, 10, 0, 0]
  | .envo01001798 => ![13, 1, 10, 0, 34, 10]
  | .envo03520006 => ![7, 17, 19, 14, 0, 0]
  | .envo03600010 => ![10, 0, 26, 7, 0, 9]
  | .envo03600077 => ![27, 6, 26, 0, 0, 0]

def atmosphericAerosolFormationMembers : List E := [.envo01001090, .envo01001091, .envo01001640]
/-- Attention profile of atmospheric aerosol formation (total 240). -/
def wAtmosphericAerosolFormation : Fin 6 → ℕ := ![95, 4, 41, 50, 31, 19]
def atmosphericAerosolFormationChi : E → Point 6 := weightedChi wAtmosphericAerosolFormation posE

def kAtmosphericAerosolFormation : KonceptN 6 E where
  pred := fun a => a ∈ atmosphericAerosolFormationMembers
  χ    := atmosphericAerosolFormationChi

def diffFormationOfASolidAerosolInAnAtmosphereMembers : List E := [.envo01001090, .envo01001640]
/-- Attention profile of diff::formation of a solid aerosol in an atmosphere (total 240). -/
def wDiffFormationOfASolidAerosolInAnAtmosphere : Fin 6 → ℕ := ![107, 12, 29, 44, 45, 3]
def diffFormationOfASolidAerosolInAnAtmosphereChi : E → Point 6 := weightedChi wDiffFormationOfASolidAerosolInAnAtmosphere posE

def kDiffFormationOfASolidAerosolInAnAtmosphere : KonceptN 6 E where
  pred := fun a => a ∈ diffFormationOfASolidAerosolInAnAtmosphereMembers
  χ    := diffFormationOfASolidAerosolInAnAtmosphereChi

def formationOfASolidAerosolInAnAtmosphereMembers : List E := [.envo01001090, .envo01001640]
/-- Attention profile of formation of a solid aerosol in an atmosphere (total 240). -/
def wFormationOfASolidAerosolInAnAtmosphere : Fin 6 → ℕ := ![107, 12, 29, 44, 45, 3]
def formationOfASolidAerosolInAnAtmosphereChi : E → Point 6 := weightedChi wFormationOfASolidAerosolInAnAtmosphere posE

def kFormationOfASolidAerosolInAnAtmosphere : KonceptN 6 E where
  pred := fun a => a ∈ formationOfASolidAerosolInAnAtmosphereMembers
  χ    := formationOfASolidAerosolInAnAtmosphereChi

/-- CCD grounding for atmospheric aerosol formation: ENVO:01001090 and ENVO:01001091 cluster against ENVO:00000172. -/
theorem atmosphericAerosolFormation_ccd_envo01001090_envo01001091 :
    SimilarByContrastN (atmosphericAerosolFormationChi .envo01001090) (atmosphericAerosolFormationChi .envo01001091) (atmosphericAerosolFormationChi .envo00000172) := by decide

/-- CCD grounding for atmospheric aerosol formation: ENVO:01001090 and ENVO:01001640 cluster against ENVO:00000172. -/
theorem atmosphericAerosolFormation_ccd_envo01001090_envo01001640 :
    SimilarByContrastN (atmosphericAerosolFormationChi .envo01001090) (atmosphericAerosolFormationChi .envo01001640) (atmosphericAerosolFormationChi .envo00000172) := by decide

/-- CCD grounding for atmospheric aerosol formation: ENVO:01001091 and ENVO:01001640 cluster against ENVO:00000172. -/
theorem atmosphericAerosolFormation_ccd_envo01001091_envo01001640 :
    SimilarByContrastN (atmosphericAerosolFormationChi .envo01001091) (atmosphericAerosolFormationChi .envo01001640) (atmosphericAerosolFormationChi .envo00000172) := by decide

/-- CCD grounding for diff::formation of a solid aerosol in an atmosphere: ENVO:01001090 and ENVO:01001640 cluster against ENVO:00000172. -/
theorem diffFormationOfASolidAerosolInAnAtmosphere_ccd_envo01001090_envo01001640 :
    SimilarByContrastN (diffFormationOfASolidAerosolInAnAtmosphereChi .envo01001090) (diffFormationOfASolidAerosolInAnAtmosphereChi .envo01001640) (diffFormationOfASolidAerosolInAnAtmosphereChi .envo00000172) := by decide

/-- CCD grounding for formation of a solid aerosol in an atmosphere: ENVO:01001090 and ENVO:01001640 cluster against ENVO:00000172. -/
theorem formationOfASolidAerosolInAnAtmosphere_ccd_envo01001090_envo01001640 :
    SimilarByContrastN (formationOfASolidAerosolInAnAtmosphereChi .envo01001090) (formationOfASolidAerosolInAnAtmosphereChi .envo01001640) (formationOfASolidAerosolInAnAtmosphereChi .envo00000172) := by decide

-- Definition 'formation of a solid aerosol in an atmosphere = diff::formation of a solid aerosol in an atmosphere atmospheric aerosol formation' FAILED the audit; not certified.
--   ✗ isEssential: unit ENVO:01001090: genus χ (2755, 0, 328, 0, 0, 228) ⊀ (incomparable or reversed) differentia χ (3103, 0, 232, 0, 0, 36); uniform-functional collapse HOLDS (3311 vs 3371)
--   ✗ isEssential: unit ENVO:01001640: genus χ (2755, 40, 0, 0, 0, 190) ⊀ (incomparable or reversed) differentia χ (3103, 120, 0, 0, 0, 30); uniform-functional collapse HOLDS (2985 vs 3253)

/-- The uniform depth functional: equal attention to every dimension. -/
def uniform : DepthFunctional 6 :=
  ⟨fun _ => 1, fun _ => Int.zero_lt_one⟩

/-- Weaker certificate for 'formation of a solid aerosol in an atmosphere = diff::formation of a solid aerosol in an atmosphere atmospheric aerosol formation': the product-order
    raise fails (genus and differentia attentions are
    incomparable), but under the uniform functional the
    differentia is deeper on every unit. Direction is
    imposed by the weighting, not discovered — exactly
    what `functionals_disagree` warns. -/
theorem formationOfASolidAerosolInAnAtmosphere_functional_essential :
    ∀ a, (a ∈ atmosphericAerosolFormationMembers ∧ a ∈ diffFormationOfASolidAerosolInAnAtmosphereMembers) →
      Raise (uniform.eval (atmosphericAerosolFormationChi a)) (uniform.eval (diffFormationOfASolidAerosolInAnAtmosphereChi a)) := by
  decide

end AuditCertENVO
