import CCDDecidable

/-!
# Machine-generated composed-audit check (CCD₃N) — do not edit

Generated by src/sigml/validate.py. Each case is a random concept over
a finite entity type; the `example` asserts the Python audit's grounding
decision (`CCD₃N k` if every member pair grounds, `¬CCD₃N k` otherwise)
and closes it by `decide`. Compiling ⇒ the Python pairs-and-witnesses
search agrees with the Lean `CCD₃N` proposition on every case — the
composed audit decision, not just the primitives.
-/

namespace ValidateComposed

def mem0 : Finset (Fin 5) := {1, 2, 3, 4}
def k0 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem0
  χ    := fun a => match a with
    | 0 => ![-2, 3] | 1 => ![-5, 5] | 2 => ![5, 1] | 3 => ![3, -1] | _ => ![-4, -3]
instance : DecidablePred k0.pred := fun a => Finset.decidableMem a mem0
example : ¬CCD₃N k0 := by decide

def mem1 : Finset (Fin 5) := {0, 2, 4}
def k1 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem1
  χ    := fun a => match a with
    | 0 => ![-5, 5] | 1 => ![0, 0] | 2 => ![-4, 2] | 3 => ![-1, -1] | _ => ![-3, -1]
instance : DecidablePred k1.pred := fun a => Finset.decidableMem a mem1
example : ¬CCD₃N k1 := by decide

def mem2 : Finset (Fin 5) := {0, 1, 4}
def k2 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem2
  χ    := fun a => match a with
    | 0 => ![-4, -5] | 1 => ![-2, -4] | 2 => ![2, 4] | 3 => ![3, -1] | _ => ![2, 0]
instance : DecidablePred k2.pred := fun a => Finset.decidableMem a mem2
example : ¬CCD₃N k2 := by decide

def mem3 : Finset (Fin 5) := {0, 4}
def k3 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem3
  χ    := fun a => match a with
    | 0 => ![3, -1] | 1 => ![-2, 0] | 2 => ![-4, 5] | 3 => ![-5, 0] | _ => ![5, 1]
instance : DecidablePred k3.pred := fun a => Finset.decidableMem a mem3
example : CCD₃N k3 := by decide

def mem4 : Finset (Fin 5) := {0, 1}
def k4 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem4
  χ    := fun a => match a with
    | 0 => ![-5, 1] | 1 => ![-4, 2] | 2 => ![-4, 1] | 3 => ![-5, 1] | _ => ![-1, -1]
instance : DecidablePred k4.pred := fun a => Finset.decidableMem a mem4
example : CCD₃N k4 := by decide

def mem5 : Finset (Fin 5) := {0, 1, 4}
def k5 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem5
  χ    := fun a => match a with
    | 0 => ![0, -3] | 1 => ![-1, -3] | 2 => ![-4, 4] | 3 => ![5, -2] | _ => ![2, 0]
instance : DecidablePred k5.pred := fun a => Finset.decidableMem a mem5
example : CCD₃N k5 := by decide

def mem6 : Finset (Fin 5) := {1, 3}
def k6 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem6
  χ    := fun a => match a with
    | 0 => ![4, 3] | 1 => ![-4, 0] | 2 => ![-4, 5] | 3 => ![4, 5] | _ => ![-2, -5]
instance : DecidablePred k6.pred := fun a => Finset.decidableMem a mem6
example : ¬CCD₃N k6 := by decide

def mem7 : Finset (Fin 5) := {2, 3, 4}
def k7 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem7
  χ    := fun a => match a with
    | 0 => ![1, -1] | 1 => ![5, -5] | 2 => ![2, -3] | 3 => ![4, -1] | _ => ![5, -4]
instance : DecidablePred k7.pred := fun a => Finset.decidableMem a mem7
example : ¬CCD₃N k7 := by decide

def mem8 : Finset (Fin 5) := {1, 2, 3, 4}
def k8 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem8
  χ    := fun a => match a with
    | 0 => ![-5, -3] | 1 => ![1, 3] | 2 => ![-4, 0] | 3 => ![1, 4] | _ => ![-4, -4]
instance : DecidablePred k8.pred := fun a => Finset.decidableMem a mem8
example : ¬CCD₃N k8 := by decide

def mem9 : Finset (Fin 5) := {0, 1}
def k9 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem9
  χ    := fun a => match a with
    | 0 => ![4, 4] | 1 => ![0, 4] | 2 => ![4, 2] | 3 => ![-3, -5] | _ => ![-1, 4]
instance : DecidablePred k9.pred := fun a => Finset.decidableMem a mem9
example : CCD₃N k9 := by decide

def mem10 : Finset (Fin 5) := {2, 3}
def k10 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem10
  χ    := fun a => match a with
    | 0 => ![1, -3] | 1 => ![-1, -2] | 2 => ![5, -5] | 3 => ![2, -3] | _ => ![-2, -2]
instance : DecidablePred k10.pred := fun a => Finset.decidableMem a mem10
example : ¬CCD₃N k10 := by decide

def mem11 : Finset (Fin 5) := {1, 3, 4}
def k11 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem11
  χ    := fun a => match a with
    | 0 => ![2, -2] | 1 => ![-4, 1] | 2 => ![5, 5] | 3 => ![2, -5] | _ => ![1, 5]
instance : DecidablePred k11.pred := fun a => Finset.decidableMem a mem11
example : ¬CCD₃N k11 := by decide

def mem12 : Finset (Fin 5) := {0, 1, 4}
def k12 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem12
  χ    := fun a => match a with
    | 0 => ![5, -5] | 1 => ![-5, -2] | 2 => ![-3, -1] | 3 => ![-4, 2] | _ => ![-4, 3]
instance : DecidablePred k12.pred := fun a => Finset.decidableMem a mem12
example : ¬CCD₃N k12 := by decide

def mem13 : Finset (Fin 5) := {0, 1, 2, 3}
def k13 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem13
  χ    := fun a => match a with
    | 0 => ![0, -1] | 1 => ![1, -1] | 2 => ![-1, -5] | 3 => ![-2, 2] | _ => ![1, 4]
instance : DecidablePred k13.pred := fun a => Finset.decidableMem a mem13
example : ¬CCD₃N k13 := by decide

def mem14 : Finset (Fin 5) := {1, 3}
def k14 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem14
  χ    := fun a => match a with
    | 0 => ![-4, -1] | 1 => ![3, 3] | 2 => ![0, 2] | 3 => ![-4, 5] | _ => ![-3, -4]
instance : DecidablePred k14.pred := fun a => Finset.decidableMem a mem14
example : CCD₃N k14 := by decide

def mem15 : Finset (Fin 5) := {1, 2, 3, 4}
def k15 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem15
  χ    := fun a => match a with
    | 0 => ![-3, -1] | 1 => ![5, -4] | 2 => ![0, 0] | 3 => ![2, 4] | _ => ![3, 3]
instance : DecidablePred k15.pred := fun a => Finset.decidableMem a mem15
example : ¬CCD₃N k15 := by decide

def mem16 : Finset (Fin 5) := {1, 2, 3, 4}
def k16 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem16
  χ    := fun a => match a with
    | 0 => ![0, -3] | 1 => ![-3, 0] | 2 => ![-1, -5] | 3 => ![3, 2] | _ => ![-3, 5]
instance : DecidablePred k16.pred := fun a => Finset.decidableMem a mem16
example : ¬CCD₃N k16 := by decide

def mem17 : Finset (Fin 5) := {3, 4}
def k17 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem17
  χ    := fun a => match a with
    | 0 => ![3, -3] | 1 => ![-1, -2] | 2 => ![-3, -4] | 3 => ![0, -4] | _ => ![5, 5]
instance : DecidablePred k17.pred := fun a => Finset.decidableMem a mem17
example : ¬CCD₃N k17 := by decide

def mem18 : Finset (Fin 5) := {2, 3, 4}
def k18 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem18
  χ    := fun a => match a with
    | 0 => ![3, 1] | 1 => ![-2, 1] | 2 => ![-1, -4] | 3 => ![-1, -5] | _ => ![1, 0]
instance : DecidablePred k18.pred := fun a => Finset.decidableMem a mem18
example : ¬CCD₃N k18 := by decide

def mem19 : Finset (Fin 5) := {0, 1, 3, 4}
def k19 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem19
  χ    := fun a => match a with
    | 0 => ![5, 0] | 1 => ![-5, -2] | 2 => ![0, -2] | 3 => ![-3, 1] | _ => ![-4, 5]
instance : DecidablePred k19.pred := fun a => Finset.decidableMem a mem19
example : ¬CCD₃N k19 := by decide

def mem20 : Finset (Fin 5) := {0, 3}
def k20 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem20
  χ    := fun a => match a with
    | 0 => ![0, -4] | 1 => ![5, 0] | 2 => ![4, 5] | 3 => ![-5, -4] | _ => ![4, 1]
instance : DecidablePred k20.pred := fun a => Finset.decidableMem a mem20
example : CCD₃N k20 := by decide

def mem21 : Finset (Fin 5) := {2, 3}
def k21 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem21
  χ    := fun a => match a with
    | 0 => ![-4, -2] | 1 => ![-4, 4] | 2 => ![-5, -4] | 3 => ![-4, -2] | _ => ![0, -2]
instance : DecidablePred k21.pred := fun a => Finset.decidableMem a mem21
example : CCD₃N k21 := by decide

def mem22 : Finset (Fin 5) := {0, 1, 2, 3}
def k22 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem22
  χ    := fun a => match a with
    | 0 => ![4, 0] | 1 => ![-3, 5] | 2 => ![-3, 1] | 3 => ![-3, -4] | _ => ![4, -4]
instance : DecidablePred k22.pred := fun a => Finset.decidableMem a mem22
example : ¬CCD₃N k22 := by decide

def mem23 : Finset (Fin 5) := {0, 1, 2, 3}
def k23 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem23
  χ    := fun a => match a with
    | 0 => ![4, 2] | 1 => ![3, 0] | 2 => ![-2, -4] | 3 => ![0, 4] | _ => ![0, -3]
instance : DecidablePred k23.pred := fun a => Finset.decidableMem a mem23
example : ¬CCD₃N k23 := by decide

def mem24 : Finset (Fin 5) := {2, 3, 4}
def k24 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem24
  χ    := fun a => match a with
    | 0 => ![-4, -2] | 1 => ![2, -3] | 2 => ![1, 0] | 3 => ![-1, 4] | _ => ![3, -2]
instance : DecidablePred k24.pred := fun a => Finset.decidableMem a mem24
example : ¬CCD₃N k24 := by decide

def mem25 : Finset (Fin 5) := {1, 2, 4}
def k25 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem25
  χ    := fun a => match a with
    | 0 => ![3, -1] | 1 => ![0, 0] | 2 => ![1, -2] | 3 => ![2, 0] | _ => ![2, -4]
instance : DecidablePred k25.pred := fun a => Finset.decidableMem a mem25
example : ¬CCD₃N k25 := by decide

def mem26 : Finset (Fin 5) := {0, 2, 3, 4}
def k26 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem26
  χ    := fun a => match a with
    | 0 => ![1, 3] | 1 => ![5, 0] | 2 => ![2, 0] | 3 => ![3, -5] | _ => ![-4, 4]
instance : DecidablePred k26.pred := fun a => Finset.decidableMem a mem26
example : ¬CCD₃N k26 := by decide

def mem27 : Finset (Fin 5) := {0, 1, 3, 4}
def k27 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem27
  χ    := fun a => match a with
    | 0 => ![4, 4] | 1 => ![-3, 4] | 2 => ![-4, 3] | 3 => ![-4, -3] | _ => ![-2, 4]
instance : DecidablePred k27.pred := fun a => Finset.decidableMem a mem27
example : ¬CCD₃N k27 := by decide

def mem28 : Finset (Fin 5) := {0, 1, 3, 4}
def k28 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem28
  χ    := fun a => match a with
    | 0 => ![0, 0] | 1 => ![1, 5] | 2 => ![2, 4] | 3 => ![-5, 0] | _ => ![-5, 3]
instance : DecidablePred k28.pred := fun a => Finset.decidableMem a mem28
example : ¬CCD₃N k28 := by decide

def mem29 : Finset (Fin 5) := {2, 3}
def k29 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem29
  χ    := fun a => match a with
    | 0 => ![-5, 0] | 1 => ![-1, -3] | 2 => ![-5, 3] | 3 => ![5, -5] | _ => ![-3, -3]
instance : DecidablePred k29.pred := fun a => Finset.decidableMem a mem29
example : ¬CCD₃N k29 := by decide

def mem30 : Finset (Fin 5) := {0, 2, 3, 4}
def k30 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem30
  χ    := fun a => match a with
    | 0 => ![2, 3] | 1 => ![4, 2] | 2 => ![1, -4] | 3 => ![1, 1] | _ => ![-1, 5]
instance : DecidablePred k30.pred := fun a => Finset.decidableMem a mem30
example : ¬CCD₃N k30 := by decide

def mem31 : Finset (Fin 5) := {0, 1, 3, 4}
def k31 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem31
  χ    := fun a => match a with
    | 0 => ![2, 3] | 1 => ![0, 4] | 2 => ![3, 5] | 3 => ![4, 1] | _ => ![-2, -3]
instance : DecidablePred k31.pred := fun a => Finset.decidableMem a mem31
example : ¬CCD₃N k31 := by decide

def mem32 : Finset (Fin 5) := {0, 1, 2, 4}
def k32 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem32
  χ    := fun a => match a with
    | 0 => ![1, 5] | 1 => ![3, -1] | 2 => ![3, -1] | 3 => ![-3, 4] | _ => ![-3, -1]
instance : DecidablePred k32.pred := fun a => Finset.decidableMem a mem32
example : ¬CCD₃N k32 := by decide

def mem33 : Finset (Fin 5) := {2, 3}
def k33 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem33
  χ    := fun a => match a with
    | 0 => ![-2, 3] | 1 => ![-2, 3] | 2 => ![3, -4] | 3 => ![-5, 3] | _ => ![-3, 3]
instance : DecidablePred k33.pred := fun a => Finset.decidableMem a mem33
example : ¬CCD₃N k33 := by decide

def mem34 : Finset (Fin 5) := {0, 1, 2, 4}
def k34 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem34
  χ    := fun a => match a with
    | 0 => ![-1, -3] | 1 => ![-1, -4] | 2 => ![2, -3] | 3 => ![5, 0] | _ => ![2, 5]
instance : DecidablePred k34.pred := fun a => Finset.decidableMem a mem34
example : ¬CCD₃N k34 := by decide

def mem35 : Finset (Fin 5) := {0, 2, 3}
def k35 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem35
  χ    := fun a => match a with
    | 0 => ![-2, -1] | 1 => ![-4, 1] | 2 => ![-2, 1] | 3 => ![4, -4] | _ => ![4, 5]
instance : DecidablePred k35.pred := fun a => Finset.decidableMem a mem35
example : ¬CCD₃N k35 := by decide

def mem36 : Finset (Fin 5) := {1, 2, 3}
def k36 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem36
  χ    := fun a => match a with
    | 0 => ![-3, 3] | 1 => ![1, 0] | 2 => ![3, -3] | 3 => ![1, 2] | _ => ![2, -4]
instance : DecidablePred k36.pred := fun a => Finset.decidableMem a mem36
example : ¬CCD₃N k36 := by decide

def mem37 : Finset (Fin 5) := {1, 2, 3, 4}
def k37 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem37
  χ    := fun a => match a with
    | 0 => ![-4, 4] | 1 => ![-1, 5] | 2 => ![-4, -3] | 3 => ![1, 4] | _ => ![-2, 5]
instance : DecidablePred k37.pred := fun a => Finset.decidableMem a mem37
example : ¬CCD₃N k37 := by decide

def mem38 : Finset (Fin 5) := {1, 2}
def k38 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem38
  χ    := fun a => match a with
    | 0 => ![-1, -5] | 1 => ![-5, 4] | 2 => ![-3, -5] | 3 => ![-2, -1] | _ => ![5, 1]
instance : DecidablePred k38.pred := fun a => Finset.decidableMem a mem38
example : CCD₃N k38 := by decide

def mem39 : Finset (Fin 5) := {2, 3, 4}
def k39 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem39
  χ    := fun a => match a with
    | 0 => ![0, 5] | 1 => ![0, 4] | 2 => ![-1, 3] | 3 => ![-2, -2] | _ => ![-3, -4]
instance : DecidablePred k39.pred := fun a => Finset.decidableMem a mem39
example : ¬CCD₃N k39 := by decide

def mem40 : Finset (Fin 5) := {1, 2, 3, 4}
def k40 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem40
  χ    := fun a => match a with
    | 0 => ![-5, -2] | 1 => ![-4, 4] | 2 => ![3, -1] | 3 => ![3, -1] | _ => ![-5, -5]
instance : DecidablePred k40.pred := fun a => Finset.decidableMem a mem40
example : ¬CCD₃N k40 := by decide

def mem41 : Finset (Fin 5) := {0, 3}
def k41 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem41
  χ    := fun a => match a with
    | 0 => ![1, -1] | 1 => ![2, 5] | 2 => ![5, 4] | 3 => ![2, -5] | _ => ![-3, -1]
instance : DecidablePred k41.pred := fun a => Finset.decidableMem a mem41
example : CCD₃N k41 := by decide

def mem42 : Finset (Fin 5) := {0, 1, 4}
def k42 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem42
  χ    := fun a => match a with
    | 0 => ![-3, -5] | 1 => ![-4, -3] | 2 => ![-5, 3] | 3 => ![1, -4] | _ => ![4, 2]
instance : DecidablePred k42.pred := fun a => Finset.decidableMem a mem42
example : ¬CCD₃N k42 := by decide

def mem43 : Finset (Fin 5) := {0, 1, 2, 3}
def k43 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem43
  χ    := fun a => match a with
    | 0 => ![-5, 3] | 1 => ![5, -3] | 2 => ![5, -2] | 3 => ![-5, 5] | _ => ![1, 2]
instance : DecidablePred k43.pred := fun a => Finset.decidableMem a mem43
example : ¬CCD₃N k43 := by decide

def mem44 : Finset (Fin 5) := {0, 1, 2, 3}
def k44 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem44
  χ    := fun a => match a with
    | 0 => ![3, 1] | 1 => ![-5, -2] | 2 => ![-2, -3] | 3 => ![5, 4] | _ => ![0, 2]
instance : DecidablePred k44.pred := fun a => Finset.decidableMem a mem44
example : ¬CCD₃N k44 := by decide

def mem45 : Finset (Fin 5) := {1, 2, 4}
def k45 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem45
  χ    := fun a => match a with
    | 0 => ![-2, -4] | 1 => ![3, -3] | 2 => ![1, -5] | 3 => ![0, -3] | _ => ![3, 1]
instance : DecidablePred k45.pred := fun a => Finset.decidableMem a mem45
example : ¬CCD₃N k45 := by decide

def mem46 : Finset (Fin 5) := {0, 1, 3, 4}
def k46 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem46
  χ    := fun a => match a with
    | 0 => ![3, -1] | 1 => ![-4, 1] | 2 => ![1, 0] | 3 => ![3, -3] | _ => ![-4, 0]
instance : DecidablePred k46.pred := fun a => Finset.decidableMem a mem46
example : ¬CCD₃N k46 := by decide

def mem47 : Finset (Fin 5) := {0, 1, 3, 4}
def k47 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem47
  χ    := fun a => match a with
    | 0 => ![-4, -4] | 1 => ![5, -2] | 2 => ![1, 2] | 3 => ![4, -3] | _ => ![2, 1]
instance : DecidablePred k47.pred := fun a => Finset.decidableMem a mem47
example : ¬CCD₃N k47 := by decide

def mem48 : Finset (Fin 5) := {1, 2, 3}
def k48 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem48
  χ    := fun a => match a with
    | 0 => ![5, -5] | 1 => ![5, -4] | 2 => ![-1, 4] | 3 => ![4, -5] | _ => ![4, 3]
instance : DecidablePred k48.pred := fun a => Finset.decidableMem a mem48
example : ¬CCD₃N k48 := by decide

def mem49 : Finset (Fin 5) := {0, 1, 3}
def k49 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem49
  χ    := fun a => match a with
    | 0 => ![-1, 4] | 1 => ![-2, 5] | 2 => ![-4, 1] | 3 => ![4, -2] | _ => ![-3, -5]
instance : DecidablePred k49.pred := fun a => Finset.decidableMem a mem49
example : ¬CCD₃N k49 := by decide

def mem50 : Finset (Fin 5) := {0, 1, 2}
def k50 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem50
  χ    := fun a => match a with
    | 0 => ![-4, -3] | 1 => ![1, -3] | 2 => ![-2, 2] | 3 => ![5, 4] | _ => ![-5, 3]
instance : DecidablePred k50.pred := fun a => Finset.decidableMem a mem50
example : CCD₃N k50 := by decide

def mem51 : Finset (Fin 5) := {1, 2}
def k51 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem51
  χ    := fun a => match a with
    | 0 => ![-3, -2] | 1 => ![0, -3] | 2 => ![-5, 3] | 3 => ![0, -5] | _ => ![-2, 1]
instance : DecidablePred k51.pred := fun a => Finset.decidableMem a mem51
example : ¬CCD₃N k51 := by decide

def mem52 : Finset (Fin 5) := {2, 3}
def k52 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem52
  χ    := fun a => match a with
    | 0 => ![4, 4] | 1 => ![-2, -3] | 2 => ![5, -3] | 3 => ![-4, 1] | _ => ![-4, 1]
instance : DecidablePred k52.pred := fun a => Finset.decidableMem a mem52
example : ¬CCD₃N k52 := by decide

def mem53 : Finset (Fin 5) := {2, 4}
def k53 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem53
  χ    := fun a => match a with
    | 0 => ![5, 3] | 1 => ![0, 3] | 2 => ![0, -5] | 3 => ![-5, -1] | _ => ![0, 2]
instance : DecidablePred k53.pred := fun a => Finset.decidableMem a mem53
example : CCD₃N k53 := by decide

def mem54 : Finset (Fin 5) := {3, 4}
def k54 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem54
  χ    := fun a => match a with
    | 0 => ![-3, 1] | 1 => ![-2, 4] | 2 => ![-2, -3] | 3 => ![-2, 1] | _ => ![-5, 0]
instance : DecidablePred k54.pred := fun a => Finset.decidableMem a mem54
example : ¬CCD₃N k54 := by decide

def mem55 : Finset (Fin 5) := {0, 2, 3, 4}
def k55 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem55
  χ    := fun a => match a with
    | 0 => ![1, 2] | 1 => ![-5, -1] | 2 => ![2, 1] | 3 => ![1, 0] | _ => ![-4, -4]
instance : DecidablePred k55.pred := fun a => Finset.decidableMem a mem55
example : ¬CCD₃N k55 := by decide

def mem56 : Finset (Fin 5) := {0, 1, 3, 4}
def k56 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem56
  χ    := fun a => match a with
    | 0 => ![3, 0] | 1 => ![-2, -3] | 2 => ![1, 3] | 3 => ![4, -3] | _ => ![-2, -1]
instance : DecidablePred k56.pred := fun a => Finset.decidableMem a mem56
example : ¬CCD₃N k56 := by decide

def mem57 : Finset (Fin 5) := {0, 1, 2, 4}
def k57 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem57
  χ    := fun a => match a with
    | 0 => ![4, 1] | 1 => ![-3, -1] | 2 => ![-4, 5] | 3 => ![-5, -2] | _ => ![-4, -4]
instance : DecidablePred k57.pred := fun a => Finset.decidableMem a mem57
example : ¬CCD₃N k57 := by decide

def mem58 : Finset (Fin 5) := {0, 1}
def k58 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem58
  χ    := fun a => match a with
    | 0 => ![-4, -2] | 1 => ![3, 3] | 2 => ![0, -5] | 3 => ![3, 2] | _ => ![0, 2]
instance : DecidablePred k58.pred := fun a => Finset.decidableMem a mem58
example : ¬CCD₃N k58 := by decide

def mem59 : Finset (Fin 5) := {0, 2, 3}
def k59 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem59
  χ    := fun a => match a with
    | 0 => ![-1, -3] | 1 => ![4, -1] | 2 => ![2, 4] | 3 => ![-3, -1] | _ => ![-1, -2]
instance : DecidablePred k59.pred := fun a => Finset.decidableMem a mem59
example : ¬CCD₃N k59 := by decide

def mem60 : Finset (Fin 5) := {1, 2, 3, 4}
def k60 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem60
  χ    := fun a => match a with
    | 0 => ![0, -3] | 1 => ![1, 5] | 2 => ![4, -5] | 3 => ![1, 3] | _ => ![2, 0]
instance : DecidablePred k60.pred := fun a => Finset.decidableMem a mem60
example : ¬CCD₃N k60 := by decide

def mem61 : Finset (Fin 5) := {0, 1, 2, 3}
def k61 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem61
  χ    := fun a => match a with
    | 0 => ![-1, -4] | 1 => ![-3, -4] | 2 => ![-4, 2] | 3 => ![5, -1] | _ => ![5, -2]
instance : DecidablePred k61.pred := fun a => Finset.decidableMem a mem61
example : ¬CCD₃N k61 := by decide

def mem62 : Finset (Fin 5) := {0, 1, 2, 3}
def k62 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem62
  χ    := fun a => match a with
    | 0 => ![-4, -2] | 1 => ![-4, -5] | 2 => ![0, -1] | 3 => ![-2, 1] | _ => ![2, 1]
instance : DecidablePred k62.pred := fun a => Finset.decidableMem a mem62
example : ¬CCD₃N k62 := by decide

def mem63 : Finset (Fin 5) := {0, 3, 4}
def k63 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem63
  χ    := fun a => match a with
    | 0 => ![-4, -1] | 1 => ![-5, -4] | 2 => ![5, -1] | 3 => ![-3, 5] | _ => ![-3, 5]
instance : DecidablePred k63.pred := fun a => Finset.decidableMem a mem63
example : ¬CCD₃N k63 := by decide

def mem64 : Finset (Fin 5) := {3, 4}
def k64 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem64
  χ    := fun a => match a with
    | 0 => ![-5, -4] | 1 => ![2, 4] | 2 => ![-4, 5] | 3 => ![1, -4] | _ => ![-3, -4]
instance : DecidablePred k64.pred := fun a => Finset.decidableMem a mem64
example : CCD₃N k64 := by decide

def mem65 : Finset (Fin 5) := {0, 1, 2}
def k65 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem65
  χ    := fun a => match a with
    | 0 => ![-2, 0] | 1 => ![-3, -5] | 2 => ![3, 1] | 3 => ![5, 4] | _ => ![-2, -1]
instance : DecidablePred k65.pred := fun a => Finset.decidableMem a mem65
example : ¬CCD₃N k65 := by decide

def mem66 : Finset (Fin 5) := {1, 2, 3}
def k66 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem66
  χ    := fun a => match a with
    | 0 => ![4, 2] | 1 => ![5, -1] | 2 => ![2, -4] | 3 => ![-5, 2] | _ => ![5, -3]
instance : DecidablePred k66.pred := fun a => Finset.decidableMem a mem66
example : ¬CCD₃N k66 := by decide

def mem67 : Finset (Fin 5) := {0, 1, 3, 4}
def k67 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem67
  χ    := fun a => match a with
    | 0 => ![-3, 3] | 1 => ![-5, 3] | 2 => ![-1, 5] | 3 => ![5, -1] | _ => ![-4, 3]
instance : DecidablePred k67.pred := fun a => Finset.decidableMem a mem67
example : ¬CCD₃N k67 := by decide

def mem68 : Finset (Fin 5) := {0, 1, 3, 4}
def k68 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem68
  χ    := fun a => match a with
    | 0 => ![5, -3] | 1 => ![0, -2] | 2 => ![4, 4] | 3 => ![-4, 3] | _ => ![-2, 5]
instance : DecidablePred k68.pred := fun a => Finset.decidableMem a mem68
example : ¬CCD₃N k68 := by decide

def mem69 : Finset (Fin 5) := {0, 1, 3}
def k69 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem69
  χ    := fun a => match a with
    | 0 => ![-1, 3] | 1 => ![2, -1] | 2 => ![4, 5] | 3 => ![-4, -1] | _ => ![2, 5]
instance : DecidablePred k69.pred := fun a => Finset.decidableMem a mem69
example : ¬CCD₃N k69 := by decide

def mem70 : Finset (Fin 5) := {1, 2, 3, 4}
def k70 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem70
  χ    := fun a => match a with
    | 0 => ![-5, 5] | 1 => ![0, 5] | 2 => ![-3, -1] | 3 => ![-1, -4] | _ => ![-3, -2]
instance : DecidablePred k70.pred := fun a => Finset.decidableMem a mem70
example : ¬CCD₃N k70 := by decide

def mem71 : Finset (Fin 5) := {0, 1, 3, 4}
def k71 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem71
  χ    := fun a => match a with
    | 0 => ![-4, 4] | 1 => ![-5, 3] | 2 => ![2, -3] | 3 => ![4, -1] | _ => ![-3, 3]
instance : DecidablePred k71.pred := fun a => Finset.decidableMem a mem71
example : ¬CCD₃N k71 := by decide

def mem72 : Finset (Fin 5) := {0, 1, 3}
def k72 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem72
  χ    := fun a => match a with
    | 0 => ![-2, 2] | 1 => ![2, 2] | 2 => ![-3, 5] | 3 => ![-1, 1] | _ => ![0, -1]
instance : DecidablePred k72.pred := fun a => Finset.decidableMem a mem72
example : CCD₃N k72 := by decide

def mem73 : Finset (Fin 5) := {1, 2, 3, 4}
def k73 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem73
  χ    := fun a => match a with
    | 0 => ![5, -5] | 1 => ![-1, 4] | 2 => ![1, 4] | 3 => ![-5, 2] | _ => ![5, 0]
instance : DecidablePred k73.pred := fun a => Finset.decidableMem a mem73
example : ¬CCD₃N k73 := by decide

def mem74 : Finset (Fin 5) := {0, 1}
def k74 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem74
  χ    := fun a => match a with
    | 0 => ![-4, 1] | 1 => ![0, 5] | 2 => ![-2, 2] | 3 => ![1, -5] | _ => ![-1, -4]
instance : DecidablePred k74.pred := fun a => Finset.decidableMem a mem74
example : CCD₃N k74 := by decide

def mem75 : Finset (Fin 5) := {0, 1, 2, 4}
def k75 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem75
  χ    := fun a => match a with
    | 0 => ![0, -2] | 1 => ![5, -4] | 2 => ![-5, 4] | 3 => ![-5, -3] | _ => ![4, 2]
instance : DecidablePred k75.pred := fun a => Finset.decidableMem a mem75
example : ¬CCD₃N k75 := by decide

def mem76 : Finset (Fin 5) := {0, 4}
def k76 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem76
  χ    := fun a => match a with
    | 0 => ![4, -4] | 1 => ![-2, 4] | 2 => ![0, -5] | 3 => ![2, 0] | _ => ![-4, -3]
instance : DecidablePred k76.pred := fun a => Finset.decidableMem a mem76
example : ¬CCD₃N k76 := by decide

def mem77 : Finset (Fin 5) := {0, 1, 3}
def k77 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem77
  χ    := fun a => match a with
    | 0 => ![4, -2] | 1 => ![3, 4] | 2 => ![3, 4] | 3 => ![-1, 4] | _ => ![2, 3]
instance : DecidablePred k77.pred := fun a => Finset.decidableMem a mem77
example : ¬CCD₃N k77 := by decide

def mem78 : Finset (Fin 5) := {2, 3, 4}
def k78 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem78
  χ    := fun a => match a with
    | 0 => ![-4, 5] | 1 => ![-5, -4] | 2 => ![2, 3] | 3 => ![0, -3] | _ => ![-5, 4]
instance : DecidablePred k78.pred := fun a => Finset.decidableMem a mem78
example : ¬CCD₃N k78 := by decide

def mem79 : Finset (Fin 5) := {0, 2, 3, 4}
def k79 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem79
  χ    := fun a => match a with
    | 0 => ![-1, -5] | 1 => ![2, 5] | 2 => ![3, 1] | 3 => ![3, -3] | _ => ![0, 0]
instance : DecidablePred k79.pred := fun a => Finset.decidableMem a mem79
example : ¬CCD₃N k79 := by decide

def mem80 : Finset (Fin 5) := {0, 2, 3, 4}
def k80 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem80
  χ    := fun a => match a with
    | 0 => ![2, 0] | 1 => ![1, 4] | 2 => ![-3, -3] | 3 => ![5, 1] | _ => ![3, 2]
instance : DecidablePred k80.pred := fun a => Finset.decidableMem a mem80
example : ¬CCD₃N k80 := by decide

def mem81 : Finset (Fin 5) := {0, 1, 3, 4}
def k81 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem81
  χ    := fun a => match a with
    | 0 => ![-4, -4] | 1 => ![2, 4] | 2 => ![0, 4] | 3 => ![-2, 5] | _ => ![-2, 0]
instance : DecidablePred k81.pred := fun a => Finset.decidableMem a mem81
example : ¬CCD₃N k81 := by decide

def mem82 : Finset (Fin 5) := {1, 4}
def k82 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem82
  χ    := fun a => match a with
    | 0 => ![-2, 1] | 1 => ![-5, 2] | 2 => ![-2, -4] | 3 => ![2, 3] | _ => ![3, 0]
instance : DecidablePred k82.pred := fun a => Finset.decidableMem a mem82
example : ¬CCD₃N k82 := by decide

def mem83 : Finset (Fin 5) := {2, 4}
def k83 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem83
  χ    := fun a => match a with
    | 0 => ![4, 5] | 1 => ![-2, 1] | 2 => ![4, -5] | 3 => ![-4, -3] | _ => ![5, 1]
instance : DecidablePred k83.pred := fun a => Finset.decidableMem a mem83
example : CCD₃N k83 := by decide

def mem84 : Finset (Fin 5) := {0, 2, 3, 4}
def k84 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem84
  χ    := fun a => match a with
    | 0 => ![2, -4] | 1 => ![5, 1] | 2 => ![-1, 5] | 3 => ![3, 0] | _ => ![-5, 3]
instance : DecidablePred k84.pred := fun a => Finset.decidableMem a mem84
example : ¬CCD₃N k84 := by decide

def mem85 : Finset (Fin 5) := {0, 3}
def k85 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem85
  χ    := fun a => match a with
    | 0 => ![-3, 2] | 1 => ![0, 1] | 2 => ![2, 0] | 3 => ![-5, -4] | _ => ![4, -4]
instance : DecidablePred k85.pred := fun a => Finset.decidableMem a mem85
example : CCD₃N k85 := by decide

def mem86 : Finset (Fin 5) := {1, 2, 3}
def k86 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem86
  χ    := fun a => match a with
    | 0 => ![0, -1] | 1 => ![0, -1] | 2 => ![4, -3] | 3 => ![-5, 0] | _ => ![-2, -4]
instance : DecidablePred k86.pred := fun a => Finset.decidableMem a mem86
example : ¬CCD₃N k86 := by decide

def mem87 : Finset (Fin 5) := {0, 1, 3}
def k87 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem87
  χ    := fun a => match a with
    | 0 => ![-4, -2] | 1 => ![5, -3] | 2 => ![-5, 5] | 3 => ![-3, 3] | _ => ![-2, -3]
instance : DecidablePred k87.pred := fun a => Finset.decidableMem a mem87
example : ¬CCD₃N k87 := by decide

def mem88 : Finset (Fin 5) := {3, 4}
def k88 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem88
  χ    := fun a => match a with
    | 0 => ![-5, 4] | 1 => ![-2, 0] | 2 => ![0, 2] | 3 => ![5, 0] | _ => ![4, -3]
instance : DecidablePred k88.pred := fun a => Finset.decidableMem a mem88
example : CCD₃N k88 := by decide

def mem89 : Finset (Fin 5) := {0, 1, 2, 4}
def k89 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem89
  χ    := fun a => match a with
    | 0 => ![-3, -1] | 1 => ![-1, 5] | 2 => ![-5, 2] | 3 => ![-1, 2] | _ => ![2, -4]
instance : DecidablePred k89.pred := fun a => Finset.decidableMem a mem89
example : ¬CCD₃N k89 := by decide

def mem90 : Finset (Fin 5) := {0, 1, 2, 4}
def k90 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem90
  χ    := fun a => match a with
    | 0 => ![4, 5] | 1 => ![2, -1] | 2 => ![3, -2] | 3 => ![-3, -1] | _ => ![-1, -2]
instance : DecidablePred k90.pred := fun a => Finset.decidableMem a mem90
example : ¬CCD₃N k90 := by decide

def mem91 : Finset (Fin 5) := {0, 2, 3, 4}
def k91 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem91
  χ    := fun a => match a with
    | 0 => ![-4, 5] | 1 => ![0, 3] | 2 => ![5, -4] | 3 => ![3, 5] | _ => ![3, 0]
instance : DecidablePred k91.pred := fun a => Finset.decidableMem a mem91
example : ¬CCD₃N k91 := by decide

def mem92 : Finset (Fin 5) := {0, 1, 3, 4}
def k92 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem92
  χ    := fun a => match a with
    | 0 => ![-1, 4] | 1 => ![4, -2] | 2 => ![5, -2] | 3 => ![1, 4] | _ => ![2, -1]
instance : DecidablePred k92.pred := fun a => Finset.decidableMem a mem92
example : ¬CCD₃N k92 := by decide

def mem93 : Finset (Fin 5) := {2, 3}
def k93 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem93
  χ    := fun a => match a with
    | 0 => ![-2, 0] | 1 => ![3, -5] | 2 => ![5, -2] | 3 => ![-1, -1] | _ => ![-5, -2]
instance : DecidablePred k93.pred := fun a => Finset.decidableMem a mem93
example : ¬CCD₃N k93 := by decide

def mem94 : Finset (Fin 5) := {0, 1, 3, 4}
def k94 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem94
  χ    := fun a => match a with
    | 0 => ![-3, 5] | 1 => ![3, -5] | 2 => ![3, -2] | 3 => ![0, -2] | _ => ![0, -3]
instance : DecidablePred k94.pred := fun a => Finset.decidableMem a mem94
example : ¬CCD₃N k94 := by decide

def mem95 : Finset (Fin 5) := {0, 1, 3}
def k95 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem95
  χ    := fun a => match a with
    | 0 => ![5, 0] | 1 => ![-2, -1] | 2 => ![4, -5] | 3 => ![-2, -4] | _ => ![3, 3]
instance : DecidablePred k95.pred := fun a => Finset.decidableMem a mem95
example : ¬CCD₃N k95 := by decide

def mem96 : Finset (Fin 5) := {2, 3}
def k96 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem96
  χ    := fun a => match a with
    | 0 => ![4, -2] | 1 => ![4, 5] | 2 => ![0, 2] | 3 => ![-5, 1] | _ => ![-2, -1]
instance : DecidablePred k96.pred := fun a => Finset.decidableMem a mem96
example : CCD₃N k96 := by decide

def mem97 : Finset (Fin 5) := {3, 4}
def k97 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem97
  χ    := fun a => match a with
    | 0 => ![-2, -1] | 1 => ![-2, 5] | 2 => ![5, 1] | 3 => ![3, 5] | _ => ![-5, 1]
instance : DecidablePred k97.pred := fun a => Finset.decidableMem a mem97
example : ¬CCD₃N k97 := by decide

def mem98 : Finset (Fin 5) := {1, 3}
def k98 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem98
  χ    := fun a => match a with
    | 0 => ![2, -3] | 1 => ![1, -1] | 2 => ![-2, -4] | 3 => ![3, 0] | _ => ![-4, 1]
instance : DecidablePred k98.pred := fun a => Finset.decidableMem a mem98
example : CCD₃N k98 := by decide

def mem99 : Finset (Fin 5) := {3, 4}
def k99 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem99
  χ    := fun a => match a with
    | 0 => ![2, 2] | 1 => ![-2, 2] | 2 => ![-3, 4] | 3 => ![1, 2] | _ => ![-4, -2]
instance : DecidablePred k99.pred := fun a => Finset.decidableMem a mem99
example : ¬CCD₃N k99 := by decide

def mem100 : Finset (Fin 5) := {0, 1, 3, 4}
def k100 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem100
  χ    := fun a => match a with
    | 0 => ![0, -1] | 1 => ![-4, 2] | 2 => ![-4, 1] | 3 => ![2, 1] | _ => ![2, 1]
instance : DecidablePred k100.pred := fun a => Finset.decidableMem a mem100
example : ¬CCD₃N k100 := by decide

def mem101 : Finset (Fin 5) := {2, 4}
def k101 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem101
  χ    := fun a => match a with
    | 0 => ![-1, -4] | 1 => ![3, 5] | 2 => ![-2, 5] | 3 => ![-5, 2] | _ => ![1, 5]
instance : DecidablePred k101.pred := fun a => Finset.decidableMem a mem101
example : CCD₃N k101 := by decide

def mem102 : Finset (Fin 5) := {1, 2, 3, 4}
def k102 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem102
  χ    := fun a => match a with
    | 0 => ![5, -1] | 1 => ![5, -5] | 2 => ![1, -2] | 3 => ![0, -3] | _ => ![-3, -4]
instance : DecidablePred k102.pred := fun a => Finset.decidableMem a mem102
example : ¬CCD₃N k102 := by decide

def mem103 : Finset (Fin 5) := {1, 4}
def k103 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem103
  χ    := fun a => match a with
    | 0 => ![-3, -5] | 1 => ![1, 2] | 2 => ![3, 3] | 3 => ![4, 0] | _ => ![-1, 2]
instance : DecidablePred k103.pred := fun a => Finset.decidableMem a mem103
example : CCD₃N k103 := by decide

def mem104 : Finset (Fin 5) := {1, 2, 4}
def k104 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem104
  χ    := fun a => match a with
    | 0 => ![-2, 3] | 1 => ![-4, 0] | 2 => ![-1, -3] | 3 => ![-4, -4] | _ => ![-3, 0]
instance : DecidablePred k104.pred := fun a => Finset.decidableMem a mem104
example : ¬CCD₃N k104 := by decide

def mem105 : Finset (Fin 5) := {0, 1, 3, 4}
def k105 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem105
  χ    := fun a => match a with
    | 0 => ![2, -4] | 1 => ![3, 1] | 2 => ![-5, 4] | 3 => ![4, 4] | _ => ![3, -1]
instance : DecidablePred k105.pred := fun a => Finset.decidableMem a mem105
example : ¬CCD₃N k105 := by decide

def mem106 : Finset (Fin 5) := {0, 1}
def k106 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem106
  χ    := fun a => match a with
    | 0 => ![2, 5] | 1 => ![-1, 1] | 2 => ![4, 3] | 3 => ![-2, 3] | _ => ![4, 0]
instance : DecidablePred k106.pred := fun a => Finset.decidableMem a mem106
example : ¬CCD₃N k106 := by decide

def mem107 : Finset (Fin 5) := {1, 2, 3}
def k107 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem107
  χ    := fun a => match a with
    | 0 => ![-4, -1] | 1 => ![0, -4] | 2 => ![-3, -2] | 3 => ![5, -3] | _ => ![-1, 2]
instance : DecidablePred k107.pred := fun a => Finset.decidableMem a mem107
example : ¬CCD₃N k107 := by decide

def mem108 : Finset (Fin 5) := {1, 3, 4}
def k108 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem108
  χ    := fun a => match a with
    | 0 => ![2, -3] | 1 => ![-2, 0] | 2 => ![-3, 2] | 3 => ![-4, 1] | _ => ![1, -5]
instance : DecidablePred k108.pred := fun a => Finset.decidableMem a mem108
example : ¬CCD₃N k108 := by decide

def mem109 : Finset (Fin 5) := {2, 3, 4}
def k109 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem109
  χ    := fun a => match a with
    | 0 => ![-1, 4] | 1 => ![0, -2] | 2 => ![-1, -5] | 3 => ![2, 2] | _ => ![-5, -4]
instance : DecidablePred k109.pred := fun a => Finset.decidableMem a mem109
example : ¬CCD₃N k109 := by decide

def mem110 : Finset (Fin 5) := {3, 4}
def k110 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem110
  χ    := fun a => match a with
    | 0 => ![3, -4] | 1 => ![-5, -3] | 2 => ![2, 0] | 3 => ![5, 3] | _ => ![1, 5]
instance : DecidablePred k110.pred := fun a => Finset.decidableMem a mem110
example : CCD₃N k110 := by decide

def mem111 : Finset (Fin 5) := {0, 1, 3, 4}
def k111 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem111
  χ    := fun a => match a with
    | 0 => ![4, 4] | 1 => ![5, -3] | 2 => ![4, -5] | 3 => ![0, 5] | _ => ![1, -4]
instance : DecidablePred k111.pred := fun a => Finset.decidableMem a mem111
example : ¬CCD₃N k111 := by decide

def mem112 : Finset (Fin 5) := {2, 3, 4}
def k112 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem112
  χ    := fun a => match a with
    | 0 => ![-2, 1] | 1 => ![1, 3] | 2 => ![3, -3] | 3 => ![0, 2] | _ => ![5, 4]
instance : DecidablePred k112.pred := fun a => Finset.decidableMem a mem112
example : ¬CCD₃N k112 := by decide

def mem113 : Finset (Fin 5) := {0, 2, 3}
def k113 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem113
  χ    := fun a => match a with
    | 0 => ![2, 5] | 1 => ![-1, -3] | 2 => ![-4, 5] | 3 => ![0, -3] | _ => ![-3, 5]
instance : DecidablePred k113.pred := fun a => Finset.decidableMem a mem113
example : ¬CCD₃N k113 := by decide

def mem114 : Finset (Fin 5) := {0, 1, 2, 4}
def k114 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem114
  χ    := fun a => match a with
    | 0 => ![-2, 3] | 1 => ![1, -4] | 2 => ![5, 2] | 3 => ![1, -2] | _ => ![-2, 2]
instance : DecidablePred k114.pred := fun a => Finset.decidableMem a mem114
example : ¬CCD₃N k114 := by decide

def mem115 : Finset (Fin 5) := {0, 1, 2, 3}
def k115 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem115
  χ    := fun a => match a with
    | 0 => ![1, 5] | 1 => ![-2, 1] | 2 => ![-4, 3] | 3 => ![-5, -4] | _ => ![-1, -1]
instance : DecidablePred k115.pred := fun a => Finset.decidableMem a mem115
example : ¬CCD₃N k115 := by decide

def mem116 : Finset (Fin 5) := {0, 1, 2, 3}
def k116 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem116
  χ    := fun a => match a with
    | 0 => ![0, -3] | 1 => ![4, 3] | 2 => ![0, -4] | 3 => ![-2, 1] | _ => ![-4, 0]
instance : DecidablePred k116.pred := fun a => Finset.decidableMem a mem116
example : ¬CCD₃N k116 := by decide

def mem117 : Finset (Fin 5) := {0, 2, 3}
def k117 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem117
  χ    := fun a => match a with
    | 0 => ![-3, 2] | 1 => ![5, 0] | 2 => ![-5, 4] | 3 => ![-5, -4] | _ => ![-1, -5]
instance : DecidablePred k117.pred := fun a => Finset.decidableMem a mem117
example : CCD₃N k117 := by decide

def mem118 : Finset (Fin 5) := {1, 2, 3, 4}
def k118 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem118
  χ    := fun a => match a with
    | 0 => ![-5, 3] | 1 => ![5, 5] | 2 => ![-2, -5] | 3 => ![-2, 3] | _ => ![-5, -1]
instance : DecidablePred k118.pred := fun a => Finset.decidableMem a mem118
example : ¬CCD₃N k118 := by decide

def mem119 : Finset (Fin 5) := {0, 1, 2, 3}
def k119 : KonceptN 2 (Fin 5) where
  pred := fun a => a ∈ mem119
  χ    := fun a => match a with
    | 0 => ![5, -4] | 1 => ![-5, -5] | 2 => ![-3, 4] | 3 => ![-1, 3] | _ => ![3, -1]
instance : DecidablePred k119.pred := fun a => Finset.decidableMem a mem119
example : ¬CCD₃N k119 := by decide

end ValidateComposed
