"""Differential validation: does the Python audit actually match the Lean spec?

The audit pipeline claims to test structures against the Lean formalization, but
`audit.py`'s predicates (`dist1`, `similar_by_contrast`, `raise_prod`) are a
hand transcription of the Lean definitions (`dist₁`, `SimilarByContrastN`,
`RaiseProd`). Nothing mechanically checks the transcription is faithful — a `<`
vs `≤` slip, an L1-vs-L2 confusion, an off-by-one in the gap inequalities would
all go uncaught, and every downstream "finding" would inherit the bug.

This module closes that gap by cross-checking the two implementations on many
random cases. For each case it computes the Python verdict, then emits a Lean
theorem asserting *that same verdict* and closes it by `decide`:

    Python says  SimilarByContrastN a b c  → emit  `example : SimilarByContrastN a b c := by decide`
    Python says ¬SimilarByContrastN a b c  → emit  `example : ¬SimilarByContrastN a b c := by decide`

If `lake build` accepts the emitted file, the Lean kernel has confirmed the
Python verdict on every case — including the negative ones, so both branches of
each predicate are exercised. If the Python and Lean implementations disagree on
any case, the emitted `decide` proves the *opposite* of what was asserted and
the build FAILS on that line, pinpointing the discrepancy.

This is the check that makes "the audit works off the Lean theory" a verified
statement rather than a claim about matching vocabulary.

    sigml validate            # regenerate SignificanceUnified/ValidateMirror.lean
    lake build                # kernel-checks Python≡Lean on every emitted case
"""

from __future__ import annotations

import os
import random
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from audit import dist1, raise_prod, similar_by_contrast  # noqa: E402

REPO = os.path.dirname(os.path.dirname(HERE))
SEED = 20260710
CASES_PER_PRED = 150      # per predicate, per dimension
DIMS = (2, 3, 5, 6)       # incl. the dims the WordNet (5) and OBO (6) audits use
COORD = 6                 # coordinates drawn from [-COORD, COORD]


def _vec(v) -> str:
    return "![" + ", ".join(str(x) for x in v) + "]"


def generate() -> str:
    rng = random.Random(SEED)
    lines = [
        "import ConceptualSpace",
        "",
        "/-!",
        "# Machine-generated Python≡Lean differential check — do not edit",
        "",
        "Generated by src/sigml/validate.py. Each `example` asserts the Python",
        "audit's verdict on a random case and closes it by `decide`. If this file",
        "compiles, the Python predicates in audit.py agree with the Lean spec",
        "(dist₁, SimilarByContrastN, RaiseProd) on every case below — both",
        "positive and negative verdicts. A transcription bug would make some",
        "emitted `decide` proof fail here.",
        "-/",
        "",
        "namespace ValidateMirror",
        "",
    ]

    def rvec(n):
        return tuple(rng.randint(-COORD, COORD) for _ in range(n))

    stats = {"sim_true": 0, "sim_false": 0, "raise_true": 0, "raise_false": 0,
             "dist": 0}

    # dist₁ — the metric agrees exactly (value equality, not just a predicate)
    lines.append("-- dist₁ : the L1 metric matches value-for-value")
    for n in DIMS:
        for _ in range(CASES_PER_PRED):
            a, b = rvec(n), rvec(n)
            lines.append(f"example : dist₁ {_vec(a)} {_vec(b)} = {dist1(a, b)} "
                         f":= by decide")
            stats["dist"] += 1
    lines.append("")

    # SimilarByContrastN — ternary similarity, both verdicts
    lines.append("-- SimilarByContrastN : ternary gap comparison")
    for n in DIMS:
        for _ in range(CASES_PER_PRED):
            a, b, c = rvec(n), rvec(n), rvec(n)
            if similar_by_contrast(a, b, c):
                lines.append(f"example : SimilarByContrastN {_vec(a)} {_vec(b)} "
                             f"{_vec(c)} := by decide")
                stats["sim_true"] += 1
            else:
                lines.append(f"example : ¬SimilarByContrastN {_vec(a)} {_vec(b)} "
                             f"{_vec(c)} := by decide")
                stats["sim_false"] += 1
    lines.append("")

    # RaiseProd — strict product order, both verdicts
    lines.append("-- RaiseProd : strict product-order level comparison")
    for n in DIMS:
        for _ in range(CASES_PER_PRED):
            a, b = rvec(n), rvec(n)
            if raise_prod(a, b):
                lines.append(f"example : RaiseProd {_vec(a)} {_vec(b)} := by decide")
                stats["raise_true"] += 1
            else:
                lines.append(f"example : ¬RaiseProd {_vec(a)} {_vec(b)} := by decide")
                stats["raise_false"] += 1
    lines.append("")
    lines.append("end ValidateMirror")
    lines.append("")

    total = sum(stats.values())
    print(f"generated {total} cross-check cases:")
    print(f"  dist₁ value-equality:      {stats['dist']}")
    print(f"  SimilarByContrastN:        {stats['sim_true']} true / "
          f"{stats['sim_false']} false")
    print(f"  RaiseProd:                 {stats['raise_true']} true / "
          f"{stats['raise_false']} false")
    if not (stats["sim_true"] and stats["sim_false"]
            and stats["raise_true"] and stats["raise_false"]):
        print("  WARNING: a verdict class is empty — widen COORD/CASES to "
              "exercise both branches")
    return "\n".join(lines)


def main() -> None:
    path = os.path.join(REPO, "SignificanceUnified", "ValidateMirror.lean")
    with open(path, "w") as fh:
        fh.write(generate())
    print(f"\nwrote {path}")
    print("run `lake build` — if it compiles, Python ≡ Lean on every case")


if __name__ == "__main__":
    main()
